### ISSUE TITLE
IRB command history not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by emmanne08** [sstephenson/rbenv#642]
Hello everyone,

I'm a first time user of Rbenv and I installed it on a Ubuntu 14.04 VM. I installed Rbenv by following the five steps found on https://github.com/sstephenson/rbenv#basic-github-checkout. Meanwhile, I installed ruby-build by running `git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build`. Then I installed Ruby 2.0.0-p451 via the command `rbenv install 2.0.0-p451` and set that as the default Ruby to use via `rbenv global 2.0.0-p451`.

Whenever I run `irb` on terminal, I am unable to use the command history via the up and down arrow keys. The characters I get are something like `^[[A` and `^[[B`. I tried doing the steps on this [stackoverflow answer](http://stackoverflow.com/a/11137143) but I wasn't able to make it work.

Could someone guide me how to make irb command history work on my environment?

**Comment by mislav** [comment]
Closing in favor of my above comment: please `apt-get install libreadline6-dev`, recompile Ruby, and try again.
