### ISSUE TITLE
RBENV_ROOT not documented

### ISSUE THREAD

**Issue by sagikazarmark** [sstephenson/rbenv#666]
I installed rbenv to `$HOME/.apps/rbenv` directory. Plugins were not working at all.

Set up everything in the profile.

The solution was: adding this to the profile:
`export RBENV_ROOT="$HOME/.apps/rbenv"`

Might worth mentioning it in the wiki or readme? Only reference I found was in the CHANGELOG.

**Comment by evaryont** [comment]
Similarilly, RBENV_HOOK_PATH isn't documented either.
