### ISSUE TITLE
Bundler requires 2.1.3?

### ISSUE THREAD

**Issue by sagikazarmark** [sstephenson/rbenv#668]
I have rbenv installed with ruby 2.1.5.

When I try to install bundler: `gem install bundler` I get an error message:

rbenv: version `2.1.3' is not installed

It is not caused by the environment, because it happens on two different macines.

**Comment by sagikazarmark** [comment]
Happy new year. :) It shows `2.1.5`.

**Comment by mislav** [comment]
@sagikazarmark Happy new year as well. And I'm sorry; I asked you for the wrong thing. I meant the full output of `rbenv version` (singular).

**Comment by mislav** [comment]
@sagikazarmark Bump. Let's get to the bottom of this and close this ticket if it's not a bug with rbenv itself.

**Comment by sagikazarmark** [comment]
@mislav Strangely I can't reproduce it now. I would say close it for now, if pops up again, I will reopen it with more details.

**Comment by mislav** [comment]
Alright thanks!
