### ISSUE TITLE
rbenv-hooks: command not found

### ISSUE THREAD

**Issue by Basmah-am** [sstephenson/rbenv#674]
Hello everyone 
When i tried to run this command on Ubuntu server :
sudo -H -S -u edxapp /bin/sh -c "HOME=/edx/app/edxapp/.rbenv RBENV_ROOT=/edx/app/edxapp/.rbenv GEM_HOME=/edx/app/edxapp/.gem PATH=/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GEM_ROOT=/edx/app/edxapp/.gem rbenv install 1.9.3-p374" 

I get an error message that says :

rbenv-hooks: command not found

**Comment by mislav** [comment]
Can you upgrade rbenv to the latest version and try again? `cd /edx/app/edxapp/.rbenv && git pull`

If that still fails, you can do `rbenv --debug install 1.9.3-p374 &> rbenv.log` and then paste `rbenv.log` into a Gist and share here.

**Comment by Basmah-am** [comment]
thank you mislav for your help
I tried the command you gave me but i got an error that says 
>cannot open .git/FETCH_HEAD: permission denied

here is the content of rbenv.log

>rbenv: no such command `--debug' 

any suggestions ?

**Comment by mislav** [comment]
Your rbenv installation is severely out of date and you can't `git pull` to update it because you don't have sufficient permissions on the fileystem. Please figure this out by yourself, as I'm not going to debug your whole server setup. Maybe simply use `sudo git pull`.

**Comment by Basmah-am** [comment]
I do not know what cause this error , I will try to discover it by myself  
thanks a lot
