### ISSUE TITLE
rbenv  install 2.2.0 fails on Linux Mint LMDE

### ISSUE THREAD

**Issue by fchampreux** [sstephenson/rbenv#675]
I am trying to install ruby on a brand new Linux Mint LMDE 201403, but it fails building Ruby.
The log reports that readline or openssl were not found, but they are actually installed. 
Is it the cause ?

    configuring openssl
    Failed to configure openssl. It will not be installed.
    configuring pathname
    configuring psych
    configuring pty
    configuring racc/cparse
    configuring rbconfig/sizeof
    configuring readline
    readline nor libedit not found
    Failed to configure readline. It will not be installed.
    configuring ripper

The 10 last lines reported are:

    installing default ripper libraries
    installing default psych libraries
    linking shared-object socket.so
    make[2]: Leaving directory `/tmp/ruby-build.20150106081213.7136/ruby-2.2.0/ext/socket'
    linking shared-object psych.so
    make[2]: Leaving directory `/tmp/ruby-build.20150106081213.7136/ruby-2.2.0/ext/psych'
    linking shared-object ripper.so
    make[2]: Leaving directory `/tmp/ruby-build.20150106081213.7136/ruby-2.2.0/ext/ripper'
    make[1]: Leaving directory `/tmp/ruby-build.20150106081213.7136/ruby-2.2.0'
    make: *** [build-ext] Error 2

Any idea to get it running ?

Thanks

Fred

**Comment by Dracyr** [comment]
I had the same problem on a brand new mint 17.1 install, after reading the ruby-build wiki and installing all dependencies it worked.
Specifically try running
```
sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
```

**Comment by fchampreux** [comment]
Great !
The dependencies were the solution !
Thanks !

2015-01-06 12:32 GMT+01:00 Per-Victor Persson <notifications@github.com>:

> I had the same problem on a brand new mint 17.1 install, after reading the
> ruby-build wiki and installing all dependencies it worked.
> Specifically try running
>
> sudo apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sstephenson/rbenv/issues/675#issuecomment-68855064>.
>



-- 

*Frédéric CHAMPREUX+41 78 87 110 55*
