### ISSUE TITLE
rbenv install 2.0.0-p247 causing errors on openssl-1.0.1e...

### ISSUE THREAD

**Issue by StuartMorris0** [sstephenson/rbenv#676]
I am trying to install the latest 2.0.0-p247 version globally and an error is occurring during the install. 

I am running : `rbenv install 2.0.0-p247`

Here is the terminal output:

```
Downloading openssl-1.0.1e.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/66bf6f10f060d561929de96f9dfe5b8c
Installing openssl-1.0.1e...

BUILD FAILED

Inspect or clean up the working tree at /var/folders/rp/lsy865ts38x8m_x2jd5lpy_c0000gn/T/ruby-build.20150107233927.14353
Results logged to /var/folders/rp/lsy865ts38x8m_x2jd5lpy_c0000gn/T/ruby-build.20150107233927.14353.log

Last 10 log lines:
installing man1/ca.1
installing man1/ciphers.1
installing man1/cms.1
cms.pod around line 457: Expected text after =item, not a number
cms.pod around line 461: Expected text after =item, not a number
cms.pod around line 465: Expected text after =item, not a number
cms.pod around line 470: Expected text after =item, not a number
cms.pod around line 474: Expected text after =item, not a number
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make: *** [install_docs] Error 255
```

The log output is fairly similar:

```
created directory `/Users/stuartmorris/.rbenv/versions/2.0.0-p247/openssl/ssl/man/man7'
installing man1/CA.pl.1
installing man1/asn1parse.1
installing man1/ca.1
installing man1/ciphers.1
installing man1/cms.1
cms.pod around line 457: Expected text after =item, not a number
cms.pod around line 461: Expected text after =item, not a number
cms.pod around line 465: Expected text after =item, not a number
cms.pod around line 470: Expected text after =item, not a number
cms.pod around line 474: Expected text after =item, not a number
POD document had syntax errors at /usr/bin/pod2man5.18 line 72.
make: *** [install_docs] Error 255
```

Any ideas on what I should do here would be appreciated.

Thanks

**Comment by mislav** [comment]
Can you upgrade ruby-build and try again?

**Comment by StuartMorris0** [comment]
Can you confirm the steps for this please. I'm not too familiar with ruby
and want to make sure I do it correctly. Thanks

**Comment by hsbt** [comment]
I thinks this issue is caused by your os environment. Please tell us your os and it's version.

**Comment by mislav** [comment]
@StuartMorris0: Certainly. The `rbenv install` command comes from the ruby-build project, which is in a separate repo on GitHub. Please see [its wiki documentation for instructions](https://github.com/sstephenson/ruby-build/wiki#updating-ruby-build) on how to upgrade. Then, `rbenv install --version` should output something like "ruby-build 20141225".

Then try the install again and paste the output again.

**Comment by StuartMorris0** [comment]
For the record I am on Yosemite 10.10.1

Thanks @mislav for your help. I ruby-build update: 
cd "$(rbenv root)"/plugins/ruby-build && git pull

Then run rbenv install again and all working fine. Appreciate the help! Thanks
