### ISSUE TITLE
more "magic" with bundle exec

### ISSUE THREAD

**Issue by bl4ckn0de** [sstephenson/rbenv#677]
I am reinstalling my rbenv now, all works, but i leave the rbev-bundler pliugin outside.

right now i am testing https://github.com/maljub01/rbenv-bundle-exec and works very well with me.

Ubuntu 14.04
zsh with oh-my-zsh, bundler, and rbenv plugin now installed.

this one works very well, with me, without need for "bundle exec" (i have a 'be' alias in zsh that works very well in any case too)

this plugin have any problem with rbenv core ? i would like to work in this too (if is needed)

**Comment by mislav** [comment]
If rbenv-bundle-exec plugin works for you, then great. We only recommend that people *don't* use rbenv-bundler because of hard-to-debug problems.

Are you actually reporting a bug? It seems like you don't have any problems yet.

**Comment by bl4ckn0de** [comment]
On Thu, Jan 8, 2015 at 12:49 PM, Mislav Marohnić 
<notifications@github.com> wrote:
> If rbenv-bundle-exec plugin works for you, then great. We only 
> recommend that people don't use rbenv-bundler because of 
> hard-to-debug problems.
> 
> Are you actually reporting a bug? It seems like you don't have any 
> problems yet.
> 


i would like to know if is posible add this plugin to rbenv core (maybe 
in some branch for integration, like rbenv-gem-rehash?) or at least 
validate that works and maintain compatibility with future rbenv 
versions.
=

**Comment by bl4ckn0de** [comment]
i will  do more tests, the plugins have problems :-( bad way... continue without this ...
