### ISSUE TITLE
Are there 2.1.4 or 2.1.5 version available via rbenv?

### ISSUE THREAD

**Issue by extempl** [sstephenson/rbenv#680]
I saw some issues in the tracker with installing 2.1.4 problems, but it even not available for me.
```
rbenv install -l
  ...
  2.1.0-preview2
  2.1.0-rc1
  2.1.1
  2.2.0-dev
  jruby-1.5.6
  jruby-1.6.3
  jruby-1.6.4
  ...
```
I'm on 10.10.1 Mac OS X

**Comment by extempl** [comment]
It fixes when I installed `ruby-build` as plugin. But why rbenv does not use that plugin by default?

**Comment by mislav** [comment]
You simply had an old version of ruby-build installed, probably via Homebrew. See https://github.com/sstephenson/ruby-build/wiki#updating-ruby-build

Now that you installed the latest as an rbenv plugin, you should remove the stale Homebrew version with `brew uninstall ruby-build`
