### ISSUE TITLE
rbenv-rehash should print where/why shims are created?

### ISSUE THREAD

**Issue by chino** [sstephenson/rbenv#685]
It's really tedious to try and track down where shims are coming from...

**Comment by mislav** [comment]
We follow the unix tools philosophy of not printing any output if the operation was a success. Once your PATH is set up for rbenv, a shim for a specific executable can easily be located by doing something like `which ruby`. You can get a list of all shims with `rbenv shims`. For a [broader look of shims and binstubs](https://github.com/sstephenson/rbenv/wiki/Understanding-binstubs), see the wiki.

**Comment by chino** [comment]
Right but you could support a debug option to print where it's being discovered?

Listing shims isn't an issue it's knowing why they are being created.

It could be any ruby version I'm using that has a gem installed or it could be a bundle in some project folder anywhere in my FS...

Something like `rbenv rehash --verbose` would be really nice.

**Comment by mislav** [comment]
Shims are only discovered in `RBENV_ROOT/versions/*/bin` directories, so it's pretty easy to locate why was one created (take a look at [`rbenv-whence` implementation](https://github.com/sstephenson/rbenv/blob/7e0e85bdda092d94aef0374af720682c6ea8999d/libexec/rbenv-whence#L21-29)). If a plugin changes this process, then it's the plugin's responsibility to document how they're doing shims. We can't know or why a 3rd party plugin decided to register a shim.

**Comment by chino** [comment]
I believe I used https://github.com/ianheggie/rbenv-binstubs but I would
have to confirm later.  It is a very handy plugin.  I wonder if it could
somehow extend the behavior of "whence" or provide it's own extended
version.
