### ISSUE TITLE
RBENV DEBUG error with scss-lint

### ISSUE THREAD

**Issue by palcisto** [sstephenson/rbenv#694]
Here you'll see the error I'm seeing in Sublime Text 3's console along with some of the processes related to my issue.
```
SublimeLinter: scss linter loaded 
reloading plugin JSLint.JSLint
reloading plugin SublimeLinter.commands
...
reloading plugin SublimeLinter.sublimelinter
...
SublimeLinter: scss activated: ['/opt/boxen/rbenv/shims/ruby', '/opt/boxen/rbenv/shims/scss-lint'] 
found 1 files for base name Flatland Dark.sublime-theme
theme loaded
Writing file /Users/palcisto/Sites/TraderTool/app/assets/stylesheets/base/_colors.scss with encoding UTF-8 (atomic)
SublimeLinter: scss: _colors.scss ['/opt/boxen/rbenv/shims/ruby', '/opt/boxen/rbenv/shims/scss-lint', '--config', '/Users/palcisto/Sites/TraderTool/.scss-lint.yml'] 
SublimeLinter: scss output:
SyntaxError: /opt/boxen/rbenv/shims/scss-lint:3: syntax error, unexpected tSTRING_BEG
[ -n "$RBENV_DEBUG" ] && set -x
     ^ 
```
My SublimeLinter 'path' settings:
```
"paths": {
    "linux": [],
    "osx": [
        "/opt/boxen/rbenv/shims",
        "/opt/boxen/rbenv/bin",
        "/opt/boxen/rbenv/plugins/ruby-build/bin"
    ],
    "windows": []
},
```
My setup:
OSX
Boxen 3.7.0
Rbenv
Sublime Text 3
SublimeLinter v3.4.31
SublimeLinter-contrib-scss-lint v1.0.3
scss-lint 0.33.0

My search has a found similar issues, but I did not find a solution to my specific issue:
[RBENV_DEBUG error with make #467](https://github.com/sstephenson/rbenv/issues/467)

Some guidance would be appreciated as any of the solutions I've attempted to implement have not fixed this for me.

I have run scss-lint from the command line and it works perfectly, it just doesn't work in SublimeText3 using SublimeLinter-contrib-scss-lint even though the plugin loads and gets activated by SublimeLinter

Edit: If this isn't the proper repo for this issue, please let me know and I'll move it to the more appropriate repo. (SublimeLinter-contrib-scss-lint or SublimeLinter)

**Comment by sstephenson** [comment]
This looks like an issue with the way SublimeLinter executes the `scss-lint` program.

Based on this line:

    SublimeLinter: scss activated: ['/opt/boxen/rbenv/shims/ruby', '/opt/boxen/rbenv/shims/scss-lint'] 

…I would guess SublimeLinter is trying to pass the path to rbenv's `scss-lint` shim to rbenv's `ruby` shim. In other words, it's trying to make Ruby execute a Bash script. Invoking `/opt/boxen/rbenv/shims/scss-lint` on its own ought to be enough.

**Comment by palcisto** [comment]
Okay, well then I'll close the issue here and open it in SublimeLinter. Thanks @sstephenson. +1
