### ISSUE TITLE
rbenv dont change ruby version

### ISSUE THREAD

**Issue by bengalamx** [sstephenson/rbenv#697]
```
MacBook-Pro-de-Miguel:mentalia Mick$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
MacBook-Pro-de-Miguel:mentalia Mick$ export PATH="$HOME/.rbenv/bin:$PATH"
MacBook-Pro-de-Miguel:mentalia Mick$ eval "$(rbenv init -)"
MacBook-Pro-de-Miguel:mentalia Mick$ rbenv global 2.2.0
MacBook-Pro-de-Miguel:mentalia Mick$ rbenv rehash
MacBook-Pro-de-Miguel:mentalia Mick$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
MacBook-Pro-de-Miguel:mentalia Mick$ bundle install
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.0
```

**Comment by mislav** [comment]
Two more steps were necessary before you did `bundle install`:

1. `gem install bundler` — you need to install Bundler in order to use it with Ruby 2.2.0
2. `rbenv rehash` — so rbenv picks up the new `bundle` executable

**Comment by bengalamx** [comment]
Thanks for the answer, i manage to make ir work, but at the time ruby 2.2.0 have a lot of bugs, so i stick with 2.1.5.

**Comment by hsbt** [comment]
@bengalamx This issue is NOT related with Ruby 2.2.0

**Comment by isabelgm** [comment]
This solved the issue I was having as well.

**Comment by xezodioud** [comment]
i searched for the answer to this issue for 9 hours

**Comment by xezodioud** [comment]
thank u

**Comment by cici-chen** [comment]
Woah I couldn't get my ruby version to update for the longest time. Not sure which command exactly did the magic but it finally updated. Thanks so much!
