### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by croaky** [sstephenson/rbenv#701]
Howdy all,

Thanks for the great work on rbenv. Would it be possible to release a new version of rbenv?

Since [0.4.0](https://github.com/sstephenson/rbenv/releases) was released, `rbenv-rehash` was merged into rbenv and other nice changes have been added.

I've been installing rbenv through Homebrew, but Homebrew sometimes removes formulas that stop making stable releases, moving them to https://github.com/Homebrew/homebrew-head-only.

Some nice things about using Homebrew without `--HEAD` include being able to have shell functions like `brew_install_or_upgrade`, consistency with other programs (Git, Vim, Hub, Postgres, etc.), and using the bottled versions (saving time on installation).

What do you think? Thanks for considering it.

Cheers,
Dan

**Comment by mislav** [comment]
Yep! 

* https://github.com/sstephenson/rbenv/issues/609#issuecomment-69810173
* https://github.com/sstephenson/rbenv/issues/587#issuecomment-42778928
* https://github.com/sstephenson/rbenv/issues/551#issuecomment-35224060
* https://github.com/sstephenson/rbenv/issues/517#issuecomment-31341669
* https://github.com/sstephenson/rbenv/issues/494#issuecomment-29342030
* https://github.com/sstephenson/rbenv/issues/604#issuecomment-48424293
