### ISSUE TITLE
Can't install `sass` correctly using `rbenv` downloaded via `homebrew`

### ISSUE THREAD

**Issue by bucaran** [sstephenson/rbenv#702]
Hey!

So, I was unable to put `sass` on my `$PATH` with

```
gem install sass
```

Unfortunately, I ran out of time and had no choice but to `sudo gem install sass` using Yosemite's default Ruby 2. This put everything in `/Library/Ruby/Gems/2.0.0` and who knows what else (how do you enable a verbose log of `gem install`'s misdeeds?) 

Ideally, using `rbenv` I should be able to install my favorite Ruby version and have gems installed inside that version's directory and symlinked to `/usrl/local/bin` or something along those lines.

I would really like to try `rbenv` again later, so any help as to what could have gone wrong would be very much appreciated.

**Comment by bucaran** [comment]
Basically, the problem was I did not add `rbenv/bin/rbenv` to `$PATH`.

    export PATH="$HOME/.rbenv/bin:$PATH

Better yet, add this to your `.bashrc` or `.bash_profile` to start every session with `rbenv`.

After that, make sure to:

    eval "$(rbenv init -)

In order to enable shims and autocompletion.


### fishshell 

For those using fish, you can accomplish the same like this:
    
    if status --is-interactive
      . (rbenv init - | psub)
    end

Now, if you don't like modifying `$PATH` directly and have ownership over `/usr/local/bin`, a more nifty solution is to symlink with `~/.rbenv/bin/rbenv`.

     ln -s ~/.rbenv/bin/rbenv /usr/local/bin

### ruby-build

As a final warning, make sure to install [`ruby-build`](https://github.com/sstephenson/ruby-build) (a `rbenv` plugin to add the `install` command to `rbenv` and be able to easily install Ruby versions.)

If you are using [homebrew](http://brew.sh) it's easy as pie:

    brew install ruby-build

### And finally `sass`

After this, install your favorited Ruby version, and go ahead and `gem install sass`, this will put it in somewhere like `Users/$USER/.rbenv/shims/sass` which is already symlinked or in the `$PATH` so it will be accessible.

_And they lived long and happily, and died together on the same day._

**Comment by mislav** [comment]
Thanks for sharing!
