### ISSUE TITLE
Rbenv and Ubunu 14.04 Terminal

### ISSUE THREAD

**Issue by kcny** [sstephenson/rbenv#703]
Hello,

I"m getting the following (please see below) in my terminal, every time I start a new terminal.  I tried restarting my computer with you luck. Do you know how I can get rid of this?

Thanks,

```
-bash: export PATH="/home/user/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/user/.rbenv/libexec/../completions/rbenv.bash'
rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`rbenv "sh-$command" "$@"`";;
  *)
    command rbenv "$command" "$@";;
  esac
}: No such file or directory
```

**Comment by mislav** [comment]
Can you share with us how you set up rbenv? Please share me the output of:

```
grep -i rbenv ~/.bash_profile ~/.bashrc ~/.profile
```

**Comment by kcny** [comment]
Sure, please see below the line.  Thanks!
---------------------------------------------------------------------
name@name-MS-7850:~$ grep -i rbenv ~/.bash_profile ~/.bashrc ~/.profile
/home/name/.bash_profile:PROMPT_COMMAND='PS1="${c_user}\u${c_reset}@${c_user}\h${c_reset}:${c_path}\w${c_reset}$(git_prompt)\$ "'eval "$(rbenv init -)"
/home/name/.profile:export PATH="$HOME/.rbenv/bin:$PATH"
/home/name/.profile:# eval

**Comment by kcny** [comment]
Thanks for this great tool by the way.  I switched from RVM to Rbenv and I'm enjoying it so far.

**Comment by kcny** [comment]
okay, I got rid of it. First I uni-stalled Rbenv and then deleted what was in the .bash_profile.  It's all solved now.  Just have to reinstal next.  Thanks!l
