### ISSUE TITLE
Your Ruby engine is ruby, but your Gemfile specified jruby

### ISSUE THREAD

**Issue by bighoax** [sstephenson/rbenv#710]
I'm working on a Jruby project, with a Gemfile defined like this :

```
ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.19'
```

When I run the ruby version :

```
ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_75-b13 +jit [darwin-x86_64]
Mic:sam$ jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_75-b13 +jit [darwin-x86_64]
```

Then when I do:

```
Mic:sam$ bundle exec rails s
Your Ruby engine is ruby, but your Gemfile specified jruby
```

What am I doing wrong here? What else can I try?

**Comment by peter-greskovic** [comment]
I had similar issue, but the message complained about different ruby versions.
When I tried to uninstall the old version of ruby using `rbenv uninstall`, I got a different error, which brought me to the source of the problem.
It seams, that some of the scripts in my local gemset (in particular the bundler stored in `.gemset_name/bin/bundler`) had for some reason the path to the old ruby interpreter hardcoded on the first line...
So no matter what the settings in the rbenv were, the script was always using the old version...

**Comment by mislav** [comment]
Yeah @peter-greskovic's advice is solid. You need to check whether running `bundle` goes through rbenv and applies proper Ruby version at runtime:

1. See `which bundle`
2. If the path is not within rbenv's `shims` directory, then you need to install Bundler in your current Ruby version and `rbenv rehash`.
3. If the path is within shims, but it still doesn't work, then uninstall rbenv plugins that provide some sort of gemset support or Bundler integration. They can mess this up.

Let us know how it goes.

**Comment by mislav** [comment]
Closing due to stale. Let me know if you still have problems!

**Comment by h4xnoodle** [comment]
@mislav 's solution worked for me.

**Comment by Deepak275** [comment]
Facing the same issue please help

**Comment by iamitpatil1993** [comment]
Facing same issue.

**Comment by hmtanbir** [comment]
@mislav 's solution worked for me.
