### ISSUE TITLE
failed to install ruby 2.2.1 with rbenv

### ISSUE THREAD

**Issue by AbhimanyuAryan** [sstephenson/rbenv#711]
Please head up to this link: http://stackoverflow.com/questions/29264711/failed-to-install-ruby-with-rbenv

I have am able to install 2.0.0-p576 with rbenv but not 2.2.1. Can you please help me fix that issue?

**Comment by mislav** [comment]
Hi, please see https://github.com/sstephenson/ruby-build/issues/728
