### ISSUE TITLE
failed gem install rails -v 4.2.0

### ISSUE THREAD

**Issue by AbhimanyuAryan** [sstephenson/rbenv#713]
I installed Ruby via rbenv. Currently, my pc has ruby 2.1.2p95 version installed. I have just started development in rails. So, don't know much about it. But, I get some kind of error when I installed it.

         $gem install rails -v 4.2.0
         ERROR:  Loading command: install (LoadError)
                     cannot load such file -- zlib
         ERROR:  While executing gem ... (NoMethodError)
                     undefined method `invoke_with_build_args' for nil:NilClass

**Comment by conflikt** [comment]
Ruby has some package dependencies, and it seems like zlib package dependency is not full-filled on your target machine.
For ubuntu its `sudo apt-get install zlib1g-dev`

**Comment by mislav** [comment]
@conflikt Thanks for the tip!

@AbhimanyuAryan If you still have problems, please open an issue in https://github.com/sstephenson/ruby-build/issues or search for related issues with "zlib".
