### ISSUE TITLE
Help with plugin authoring

### ISSUE THREAD

**Issue by jasonkarns** [sstephenson/rbenv#716]
I'm looking for some direction with regards to how to determine the rbenv root from within a plugin.

The wiki [states](https://github.com/sstephenson/rbenv/wiki/Authoring-plugins#environment) that the `$RBENV_ROOT` variable will be set as part of the environment when the plugin runs. This rather clearly implies that `$RBENV_ROOT` is safe to use.

But further along in the wiki, authors are [instructed](https://github.com/sstephenson/rbenv/wiki/Authoring-plugins#calling-other-commands) to use rbenv commands for inspecting the environment instead of constructing it themselves. This seems to imply that invoking `$(rbenv-root)` would be preferred.

Normally, it wouldn't matter, but I've encountered a weird bug (#715) with rbenv-update where `$RBENV_ROOT` isn't set in the environment as it should be.

Which is the recommended use? `$RBENV_ROOT` or `$(rbenv-root)`?

**Comment by mislav** [comment]
The docs are correct: RBENV_ROOT will always be available. Closing in favor of further discussion in #715
