### ISSUE TITLE
bundle exec rails console production doesnt work

### ISSUE THREAD

**Issue by henjin** [sstephenson/rbenv#718]
hi, im trying to run on my server bundle exec rails console production but it doesnt work, it shows

Usage:
  rails new APP_PATH [options]
....

im using:
rbenv 0.4.0-146-g7ad01b2
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
Rails 4.2.1
Gem 2.4.5

**Comment by mislav** [comment]
Any rbenv plugins installed?

**Comment by henjin** [comment]
no its a vanila rbenv

**Comment by mislav** [comment]
I don't know what the problem might be, I'm sorry. Most likely it's not rbenv, though, since your command ran fine. Something was wrong with the arguments.

**Comment by henjin** [comment]
i think i solved mystery, its becouse of capistrano 3, removed bin directory from linked_dirs

**Comment by mislav** [comment]
Glad you solved it!
