### ISSUE TITLE
rbenv help lists apparently nonexistent command 'shell'?

### ISSUE THREAD

**Issue by lpar** [sstephenson/rbenv#719]
% rbenv 
    rbenv 0.4.0
    Usage: rbenv <command> [<args>]
    
    Some useful rbenv commands are:
       commands    List all available rbenv commands
       local       Set or show the local application-specific Ruby version
       global      Set or show the global Ruby version
       shell       Set or show the shell-specific Ruby version
       install     Install a Ruby version using ruby-build
       rehash      Rehash rbenv shims (run this after installing executables)
       version     Show the current Ruby version and its origin
       versions    List all Ruby versions available to rbenv
       which       Display the full path to an executable
       whence      List all Ruby versions that contain the given executable
    
    See `rbenv help <command>' for information on a specific command.
    For full documentation, see: https://github.com/sstephenson/rbenv#readme
    % rbenv shell
    rbenv: no such command `shell'
    %

**Comment by mislav** [comment]
`rbenv shell` is available when you complete the install process listed in the README and have this line in your shell initialization file: `eval "$(rbenv init -)"`

**Comment by lpar** [comment]
Aha! Thanks. At some point I had some path problems and reworked my `.zshenv` to put all the path manipulation in one place, and although I kept rbenv's directories in the path, I forgot to make it run `$(rbenv init -)` afterwards. I hadn't noticed for months because everything kept working until I went to test a new Ruby version...
