### ISSUE TITLE
Using rbenv in a production environement

### ISSUE THREAD

**Issue by jwilczek** [sstephenson/rbenv#724]
I'm using rbenv and am trying to get a ruby application running in production.  Currently, I have everything installed and working properly in development.

I cannot figure out how to get unicorn to run in a startup script (/etc/init.d/unicorn).  When I try to start the service (sudo service unicorn start) I get the following error:
     Could not find rake-10.3.2 in any of the sources
     Run `bundle install` to install missing gems.

I believe this is a result of using the sudo command as if I run the $CMD being used to start unicorn at an unprivileged command prompt, it works perfectly fine.

I'd greatly appreciate any support on this issue.  Thank you!

**Comment by mislav** [comment]
In sudo mode, PATH will be different. There will be no rbenv shims on the PATH, and most likely the wrong Ruby version will be used. Also, in sudo mode, HOME directory might be different. If your `rbenv root` is at the default location, that will be `$HOME/.rbenv` for your user.

So, to fix running Ruby scripts from sudo just as you would from your user, you need to ensure this in your init.d script:

```sh
export RBENV_ROOT="/home/my-user/.rbenv"
export PATH="$RBENV_ROOT/.rbenv:$PATH"
```
