### ISSUE TITLE
Set ruby version from Gemfile if .ruby-version file is missing

### ISSUE THREAD

**Issue by dbackeus** [sstephenson/rbenv#727]
Not sure about all pros/cons for this but it seems configuring ruby version in two different files (`Gemfile` for Heroku and bundler / `.ruby-version` for rbenv) seems like one file too many.

I would expect rbenv to scan Gemfile for ruby version unless a .ruby-version file was present.

Makes sense?

**Comment by jasonkarns** [comment]
there's a plugin that does this: https://github.com/aripollak/rbenv-bundler-ruby-version

But it's kind of buggy. The gemfile-specified ruby isn't respected when interrogating `rbenv version` which makes most PS1 statuses misleading.

I don't think it plays well with rbenv-binstubs, either.

**Comment by mislav** [comment]
Sorry for late reply. Yes, this is plugin material. The plugin is probably buggy because there's no easy way to hook into version lookup process. I will think about whether we can make this hookable.

However, I don't see it as a huge problem if there is both a `.ruby-version` and `ruby` statement in the Gemfile. It doesn't seem like such a huge developer pain that we absolutely must solve.

**Comment by jasonkarns** [comment]
I don't believe that having both `.ruby-version` and Gemfile `ruby` directive is the problem. But rather, the desire to *only* use the `Gemfile`. I still think this belongs as a plugin, so this issue could probably be closed.

But I think rbenv could make this hookable. To that end, I've been playing around with creating `version-name` and `version-origin` hooks. As a test case, I've been using a modified version of the `rbenv-bundler-ruby-version` plugin as the consumer of those hooks. It's working quite well and I hope to have a PR ready tomorrow, where discussion can continue.

**Comment by mislav** [comment]
> As a test case, I've been using a modified version of the rbenv-bundler-ruby-version plugin as the consumer of those hooks

Sounds good, thanks!

**Comment by dbackeus** [comment]
Knew about the plugin but wanted to avoid forcing everyone on a big dev-team to install it.

Considering this is becoming the de-facto way of specifying a ruby-version for a project it seems sensible for rbenv to use it by default. Principle of least surprise, convention over configuration and all that...

**Comment by jasonkarns** [comment]
@mislav PR #739 opened for discussion

**Comment by jasonkarns** [comment]
@dbackeus you've probably already seen this, too. but here's the original issue/comments/decision regarding Gemfile #223.

**Comment by dbackeus** [comment]
Thanks for the issue link, I hadn't seen it actually. Guess this is sort of a duplicate then. But maybe feels more relevant now that more or less everyone specifies their ruby version in the Gemfile?

**Comment by mislav** [comment]
@dbackeus Yep, not such a stretch anymore. However, I feel that this is still plugin material. Moreover, if we tweak rbenv to allow plugin hooks for this, then other people could come up with even cleverer version selection. Closing this in favor of @jasonkarns's PR.

**Comment by codyrobbins** [comment]
I wish this decision would be revisited now that Bundler is the de facto dependency manager for Ruby. Shouldn’t simplicity for the end user trump simplicity of the internals of the tool? The fact that you have to specify the same Ruby version in two separate places just seems inelegant and unnecessary to me at this point—the `.ruby-version` file has become superfluous. I understand the argument for keeping this functionality in a plugin, but a plugin a poor solution in a team environment. Rbenv has become such an indispensable part of so many people’s Ruby toolboxes that I think it warrants slightly tighter integration with other crucial tools like Bundler.

**Comment by Dom-R** [comment]
I agree with @codyrobbins , maybe it is time to revisit this issue.
My workplace is already in the process of migrating from `.ruby-version` to `Gemfile`.

**Comment by jeppester** [comment]
I believe that not having support for versions specified through Gemfiles will push users towards switching to rvm because it works "out of the box" and therefore is easier to use and recommend in a team environment.

**Comment by Dom-R** [comment]
After reading @jeppester comment, I wanted to give an update that this has been one of major reasons why I changed recently to `rvm` and have been recommending it instead of `rbenv`.

**Comment by fny** [comment]
Just wanted to leave a note here for posterity: since a Gemfile is Ruby, you can always parse a ruby-version file to determine the version for the Gemfile:

```
ruby File.read('.ruby-version').strip
```

**Comment by mgomes** [comment]
For posterity, Bundler >=2.5.1 and Rubygems >=3.4.20 now support a file argument when specifying the ruby version in the Gemfile. For example:

```ruby
source 'https://rubygems.org'

ruby 3.3.0
```

can now become

```ruby
source 'https://rubygems.org'

ruby file: '.ruby-version'
```

**Comment by codyrobbins** [comment]
The lack of this feature is one of the things that ultimately motivated me to move to [`asdf`](https://asdf-vm.com).
