### ISSUE TITLE
0.4.0 "fork: retry: No child processes" when executing `rbenv install --list`

### ISSUE THREAD

**Issue by jmoody** [sstephenson/rbenv#728]
```
*      MacOS 10.10.3
*       brew 0.9.4
*      rbenv 0.4.0
* ruby-build 20150502
```

A couple of weeks ago, rbenv started to throw:

```
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: Resource temporarily unavailable
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: No child processes
```

when trying to install or list known rubies.

This is happening on 3 different boxes with very similar configurations.

Please let me know if you need more details.

### Reproduce

1. `$ rbenv local 2.2.1`
2. `$ rbenv install --list`

### Expected

To see a list of rubies available to install.

### Found

This output repeats indefinitely:

```
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: Resource temporarily unavailable
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: No child processes
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: No child processes
...
```

### Notes

Ruby-build appears to be working:

```
$ ruby-build --definitions
```

Thinking that I might have the install arguments wrong:

```
$ rbenv help install
Sorry, this command isn't documented yet.
```

which was also unexpected.

**Comment by baparanj** [comment]
Homebrew 0.9.5
Mac OS 10.10.3
When installing unicorn, getting error: /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: Resource temporarily unavailable

**Comment by mislav** [comment]
Any rbenv plugins installed such as "rbenv-gemset"? https://github.com/sstephenson/rbenv/issues/87#issuecomment-2118169

**Comment by jmoody** [comment]
In my case, I have default-gems installed.

https://github.com/sstephenson/rbenv-default-gems

I tried disabling rbenv-default-gems but found the same result.

```
$ mv ~/.rbenv/default-gems ~/.rbenv/default-gems.bak
$ brew uninstall rbenv-default-gems
$ rbenv rehash
$ rbenv install --list
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: Resource temporarily unavailable
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: No child processes
< snip >
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: Resource temporarily unavailable
/usr/local/bin/brew: fork: Resource temporarily unavailable
< snip >
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: retry: No child processes
< snip >
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv: fork: Resource temporarily unavailable
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version-name: fork: retry: No child processes
< snip >
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version-name: fork: Resource temporarily unavailable
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version-name: fork: retry: No child 
```

**Comment by mislav** [comment]
@jmoody Can you try with latest version of rbenv? `brew install --HEAD rbenv`

**Comment by jmoody** [comment]
@mislav Gladly!

```
$ brew unlink rbenv
Unlinking /usr/local/Cellar/rbenv/0.4.0... 2 symlinks removed
$ brew install --HEAD rbenv
==> Cloning https://github.com/sstephenson/rbenv.git
Cloning into '/Library/Caches/Homebrew/rbenv--git'...
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 78 (delta 1), reused 36 (delta 0), pack-reused 0
Unpacking objects: 100% (78/78), done.
Checking connectivity... done.
==> Checking out branch master
==> Caveats
To use Homebrew's directories rather than ~/.rbenv add to your profile:
  export RBENV_ROOT=/usr/local/var/rbenv

To enable shims and autocompletion add to your profile:
  if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
==> Summary
🍺  /usr/local/Cellar/rbenv/HEAD: 65 files, 288K, built in 2 seconds
$ rbenv rehash
$ rbenv install --list
```

The output was different: no more 'fork' messages, but there was no output.

I also tried a brew uninstall.

When terminating the process, I noticed that my system ruby was working at something:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
```

This really bugs me.  I am not suggesting that rbenv is at fault.  What upsets me is that every time I update my Xcode/Command line tools, I have to do a dance to figure out how to get my system to forget about the system ruby.

**Comment by mislav** [comment]
Do rbenv core commands (other than `rbenv install`) have any output at all?

**Comment by jmoody** [comment]
@mislav 

Yes.  I haven't checked all commands, but normal dev operations like setting the local ruby version or changing the global version work.

Is there a specific command you'd like me to try?

Thanks!

**Comment by mislav** [comment]
I'd just like to know whether anything other than `rbenv install --list` is broken.

**Comment by jmoody** [comment]
This command hangs:

```
$ rbenv version
2.2.1 (set by /Users/moody/.rbenv/version)
$ rbenv install 2.2.2
^C/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:7:in `<module:RbConfig>': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
```

but this does not:

```
$ rbenv uninstall 2.1.1
```

Is it normal to see the system ruby involved in an rbenv install?

**Comment by jmoody** [comment]
@mislav 

I found the RBENV_DEBUG variable.

It looks like these two variables are being concatenated indefinitely:

```
+ [rbenv:76] export PATH=
+ [rbenv:81] RBENV_HOOK_PATH=
```

On the first iteration, the value of PATH and RBENV_HOOK_PATH look correct.  On the second iteration, the values of each have been concatenated.  This continues indefinitely.

eg.

```
 RBENV_HOOK_PATH=:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/moody/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/HEAD/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
```

**Comment by jmoody** [comment]
@mislav I would be willing to give you access to my machine via an ssh connection.

**Comment by mislav** [comment]
@jmoody Sure let's try that. [My public keys](https://api.github.com/users/mislav/keys) are available from GitHub API. You can easily install them with github-auth gem: `gh-auth add mislav`

**Comment by jmoody** [comment]
@mislav 

Can I contact you @ your GitHub email address?

**Comment by mislav** [comment]
Yep that's why it's there for

**Comment by jmoody** [comment]
Turned out to be my fault.  I had an executable in my path `rbenv-install` that was causing a recursive call.

Thanks @mislav!

:+1:

**Comment by halo** [comment]
What are the odds. I had an executable `bin/docs` containing this line:

```bash
echo "  Removing directory `docs`..."
```

But I didn't notice at first that the backticks tried to execute the same executable again.

Thanks to this post I could trace it away from rbenv to my code :)
