### ISSUE TITLE
homebrew package appears to be over 2 years old.

### ISSUE THREAD

**Issue by zachdaniel** [sstephenson/rbenv#729]
I believe homebrew looks for the latest 'release', and it appears you've been doing quite a bit of work on rbenv but haven't made an actual release since then, leaving users who rely on homebrew as their package manager to be very far behind, and miss updates.

**Comment by ryh** [comment]
> brew info rbenv
> rbenv: stable 0.4.0, HEAD
> https://github.com/sstephenson/rbenv

you were saying?
did you forget to `brew update`?

**Comment by mislav** [comment]
@zachdaniel I'm sorry about the lack of releases and the late reply. Many people have been asking for a new Homebrew release: https://github.com/sstephenson/rbenv/issues/701#issuecomment-77677557

It's coming soon, but until then, you can always `brew upgrade hub --HEAD` to get the master version.
