### ISSUE TITLE
Question/Idea: ability to install and update something like "2.1-latest"?

### ISSUE THREAD

**Issue by alanfranz** [sstephenson/rbenv#734]
Hello,
first, a clarification: I like using rbenv & rbenv-build without the shims, by referring directly to the interpreter (then I use bundler with binstubs & shebang to create binstubs that directly point to the proper interpreter); I prefer this way since it removes a level of indirection caused by the shims/variables (especially useful in nonteractive environments, as build scripts, ecc). 

In my workflow I install a ruby interpreter, I update rubygems, and I install bundler, **nothing else**; the ruby interpreter is as clean as possible and everything is done via bundler with a specific path. This way I keep the concerns (project vs basic interpreter) quite decoupled.

By the way, what I'd like to do is to have something like

```
rbenv install 2.1-latest
```

such command should fetch the latest **stable** release for the 2.1 series (i.e. 2.1.6 as of this writing) and create a symlink for it in ```~/.rbenv/versions/2.1-latest``` (or maybe just ```~/.rbenv/versions/2.1```)

This way I could just use something like

```
~/.rbenv/versions/2.1-latest/bin/ruby
```

Without minding what's actually the currently latest revision of ruby (and without needing to explicitly update the minor revision in my own project)

Two questions:

1) is there any way to perform such task in the current rbenv status quo?
2) would you accept a pull request for such a feature? Where do you think it belongs? To a separate plugin or to a patch to ruby-build?

**Comment by mislav** [comment]
Historically, rbenv avoided implemented such features. You should [take a look at available plugins](https://github.com/sstephenson/rbenv/wiki/Plugins#approved-plugins) and consider using something like [rbenv-aliases](https://github.com/tpope/rbenv-aliases).
