### ISSUE TITLE
bin path doesn't come from gem env

### ISSUE THREAD

**Issue by quinn** [sstephenson/rbenv#737]
Shouldn't it? it's hardcoded to:

```
RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
```

but if gem env has a different `EXECUTABLE DIRECTORY` rbenv will not be able to find the executable. Is the user expected to configure this properly at build time for their ruby?

**Comment by mislav** [comment]
rbenv works best if all the executables are within the Ruby version's `bin` directory, as you noticed. If they are in another location, they can't be discovered without the use of a plugin.

I was working on built-in support for executables in user's home install location (`~/.gem`), but it's not yet merged: #639.

In your case, where is the EXECUTABLE_DIRECTORY located?

**Comment by quinn** [comment]
it is `/usr/local/src/rubinius/gems/bin`. The fix I have right now is `/usr/local/src/rubinius/gems/bin` is a symlink to `/usr/local/src/rubinius/bin`which works fine. Also, `~/.rbenv/versions/rbx` is a symlink to `/usr/local/src/rubinius`.

**Comment by mislav** [comment]
When installed by ruby-build, all rbx installations will have their `gems/bin` symlinked simply as `bin` https://github.com/sstephenson/ruby-build/blob/a5d0479af7ca59e9b31f52156d6b38887f68bf24/bin/ruby-build#L681-693

**Comment by quinn** [comment]
ah. so this is a known thing. Thank you! it still seems like it would be smart to use the gem env, but maybe that is a bad idea / not possible for reasons I don't understand. thanks for your help either way.

**Comment by mislav** [comment]
It's possible, it would just [make rbenv code more complex](https://github.com/sstephenson/rbenv/pull/461#issuecomment-26332992) and I've decided not to tackle that problem in rbenv core because I'm not a fan of Rubinius having gem executables separate in `gems/bin`.
