### ISSUE TITLE
Understanding rbenv file structure & folder creation

### ISSUE THREAD

**Issue by thecuriousgee** [sstephenson/rbenv#748]
I'm trying to understand how rbenv chooses a version of a ruby library to install and where it installs it.

After installing rbenv & rbuild, I installed both ruby v 2.2.0 and ruby v 2.2.2 on my local machine.  So I have two separate folders inside of .rbenv/versions: versions/2.2.2 & versions/2.2.0
However, when I look deeper into the actual folders that were created, I have these subfolders: .rbenv/versions/2.2.2/lib/ruby/2.2.0/ & .rbenv/versions/2.2.0/lib/ruby/2.2.0/

Why are both sub folders lib/ruby/2.2.0? Shouldn't ruby/2.2.2 be installed in this folder: rbenv/versions/2.2.2/lib/ruby/ ?

**Comment by mislav** [comment]
That's a good question. The `versions/2.2.2/lib/ruby/2.2.0/` directory that you found is just Ruby's way of stating that its standard libary is "2.2.0"-compatible. It's an internal convention of structuring Ruby standard library and gems during a single minor version series and is nothing to worry about. That doesn't mean that the 2.2.2 version that you've installed is somehow invalid or broken.
