### ISSUE TITLE
rbenv: no such command `install'

### ISSUE THREAD

**Issue by bryan1anderson** [sstephenson/rbenv#749]
Trying to install ruby using

   rbenv install 2.2.2
    rbenv global 2.2.2

Ends with:
    rbenv: no such command `install'

When trying to install rbenv I get this error:
    Warning: rbenv-0.4.0 already installed 
    ==> Installing dependencies for ruby-build: pkg-config, makedepend, opens
    ==> Installing ruby-build dependency: pkg-config
    ==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz
    Already downloaded: /Library/Caches/Homebrew/pkg-config-0.28.tar.gz
    ==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.28 --disable-host-tool -
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/private/tmp/pkg-config20150616-4153-mpuu6o/pkg-config-0.28':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details

**Comment by bryan1anderson** [comment]
used this line to install rbenv and ruby: brew `install rbenv ruby-build`

**Comment by mislav** [comment]
It seems that `brew install ruby-build` failed. Could you run `brew doctor` and resolve all the issues, then try that again?

**Comment by putztzu** [comment]
To me, you seem to be mixing up different commands and errors in your one post.

1. If you follow the rbenv documentation, aren't you using git clone to write a working tree and not installing? IMO that should be the most straightforward approach to "installing" with least chance to cause an error.

2. I assume that you're running "rbenv install 2.2.2" separately and must succeed before you can set a successfully installed 2.2.2 globally. You can run this only after successfully installing rbenv. I also discovered that if the instructions for installing rbenv in a User's Home directory is followed, you have to run rbenv with ordinary User permissions. When I "su" or "sudo" and run rbenv commands on an LXDE machine, I don't have issues, but on a KDE machine anomalies happened including the "install" command suddenly isn't found while many other rbenv commands continue to work.

**Comment by mislav** [comment]
@putztzu It's alright for the OP to install rbenv and ruby-build using Homebrew. However if they're going to do that, then they have to solve whatever compilation issue they have while installing ruby-build dependencies (namely "pkg-config").

Closing because the solution to this is to properly install ruby-build using either git clone or the package manager of your choice (Homebrew). However, the installation needs to complete without problems.
