### ISSUE TITLE
looping .bash_profile

### ISSUE THREAD

**Issue by scott-knight** [sstephenson/rbenv#751]
I found something odd recently while trying to edit a .bash_profile (file) on a server. 
I recently wiped my hard drive and reinstall OS X Yosemite and installed rbenv via BREW.

When you have this code added to your own .bash_profile
```
eval "$(rbenv init -)" 
```
Anywhere you type the word ".bash_profile", it copies the contents of .bash_profile in place of the word. This happens in any application you use, i.e. terminal, iTerm, chrome, anywhere you type the word, it literally, instantly copies the contents of the file in place of the word. This happens using BREW install or using the install as describe on the rbenv homepage.

If anyone has any ideas as to why, i would be interested in knowing what to do about it.

**Comment by mislav** [comment]
Are you sure this is because of rbenv? It couldn't be something like TextExpander or similar?

**Comment by scott-knight** [comment]
You are actually correct. I have done some other testing, and it is not the issue. Oddly enough, when i commented out the line, as shown above, the issue went away. However, after doing some more tests, it doesn't appear to be the culprit. I can reproduce the issue even without that line in my .bash_profile. I am not using TextExpander. However, one of the tools I install via BREW is causing the issue. I haven't been able to which one is causing it yet.

I apologize for the false alarm and I appreciate your quick response.

**Comment by scott-knight** [comment]
I figured it out! The app "Dash" has a copy of my .bash_profile as one my snippets. If Dash is open, I have the issue. If Dash is closed, it goes away. I have looked in Dash settings, but I cant find any setting that would cause it.
