### ISSUE TITLE
`rbenv versions` causes infinite loop

### ISSUE THREAD

**Issue by macroscopicentric** [sstephenson/rbenv#752]
When using `rbenv versions`, Terminal cycles through readlink, head, and bash.

I'm assuming you need more info, but not sure what else to include, sorry!

**Comment by mislav** [comment]
Hi, sorry for late reply. Is this still a problem for you? I never heard a similar report. Could it be something on your system?

Can you paste us the output of:

```
bash -c 'IFS=:; for p in $PATH; do ls -l $p/rbenv* 2>/dev/null; done'
```

**Comment by macroscopicentric** [comment]
This doesn't happen anymore, and it was so long ago that I don't remember what troubleshooting steps I took, unfortunately. Here's the bash output you asked for:
```
lrwxr-xr-x  1 rachel  wheel  31 Jun 13 14:24 /usr/local/bin/rbenv -> ../Cellar/rbenv/0.4.0/bin/rbenv
lrwxr-xr-x  1 rachel  wheel  47 Jun 13 14:24 /usr/local/bin/rbenv-install -> ../Cellar/ruby-build/20150519/bin/rbenv-install
lrwxr-xr-x  1 rachel  wheel  49 Jun 13 14:24 /usr/local/bin/rbenv-uninstall -> ../Cellar/ruby-build/20150519/bin/rbenv-uninstall
lrwxr-xr-x  1 rachel  wheel  31 Jun 13 14:24 /usr/local/bin/rbenv -> ../Cellar/rbenv/0.4.0/bin/rbenv
lrwxr-xr-x  1 rachel  wheel  47 Jun 13 14:24 /usr/local/bin/rbenv-install -> ../Cellar/ruby-build/20150519/bin/rbenv-install
lrwxr-xr-x  1 rachel  wheel  49 Jun 13 14:24 /usr/local/bin/rbenv-uninstall -> ../Cellar/ruby-build/20150519/bin/rbenv-uninstall
```
Feel free to close this issue since I can't reproduce it. Thanks!

**Comment by mislav** [comment]
Output looks fine. Yeah, must be a temporary glitch! Thanks for the update
