### ISSUE TITLE
Only Ruby 2.2.2 installs, all other Ruby versions install fail looking for "-lyaml"

### ISSUE THREAD

**Issue by putztzu** [sstephenson/rbenv#753]
Very odd.
Brand new openSUSE 13.2.
Successfully used rbenv to install  ruby 2.2.2 and that mostly works except for an error installing rails (but that will be discussed elsewhere). So, have been attempting to install any other Ruby version.

Same error returned for others, the following is an example. I've also run with the verbose flag, but I don't see any more useful info, the error lines are exactly the same with no further detail. For some odd reason, I would expect that the "ld" binary should be looking for "yaml" but instead is looking for "-lyaml" and of course no file with that name exists.

TIA.

```
> rbenv install 2.1.0
Downloading yaml-0.1.6.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7da6971b4bd08a986dd2a61353bc422362bd0edcc67d7ebaac68c95f74182749
Installing yaml-0.1.6...
Installed yaml-0.1.6 to /home/user/.rbenv/versions/2.1.0

Downloading ruby-2.1.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/3538ec1f6af96ed9deb04e0965274528162726cc9ba3625dcf23648df872d09d
Installing ruby-2.1.0...

BUILD FAILED (openSUSE project 13.2 using ruby-build 20150519-13-g702b410)

Inspect or clean up the working tree at /tmp/ruby-build.20150629205027.40381
Results logged to /tmp/ruby-build.20150629205027.40381.log

Last 10 log lines:
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lyaml
collect2: error: ld returned 1 exit status
Makefile:452: recipe for target '../../.ext/x86_64-linux/psych.so' failed
make[2]: *** [../../.ext/x86_64-linux/psych.so] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20150629205027.40381/ruby-2.1.0/ext/psych'
exts.mk:190: recipe for target 'ext/psych/all' failed
make[1]: *** [ext/psych/all] Error 2
make[1]: Leaving directory '/tmp/ruby-build.20150629205027.40381/ruby-2.1.0'
uncommon.mk:180: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2

```

**Comment by db0sch** [comment]
Hi, 
I went through the same issue...
And I sorted all out by re-installing all the necessaries packages : 
```
zypper in ruby rubygem-bundler nodejs git    gcc make libopenssl-devel sqlite3-devel'
```

Can you try to install these packages, and re-try the rbenv ruby installation ?

**Comment by mislav** [comment]
It definitely sounds like you have to install libyaml on your system, @putztzu. Try "libyaml" or "yaml-devel"

**Comment by mislav** [comment]
If you still have build problems, please report at https://github.com/sstephenson/ruby-build/issues instead since rbenv itself is not responsible for installing Rubies, just switching them.
