### ISSUE TITLE
Shims path not added to $PATH on fish on Ubuntu 14.04

### ISSUE THREAD

**Issue by Hettomei** [sstephenson/rbenv#755]
Hi,

I used rbenv for more than 2 years now so : Thank you :) 

Recently I try the shell "fish"

When I go in a project which has a .ruby-version defined, it didn't change : when I type ```ruby --version``` it is not the same as ```cat .ruby-version```

To init rbenv inside ~/.config/fish/config.fish I have wrote : 
```
. (rbenv init -)
```
But when I do ```echo $PATH``` there is no ```$HOME/.rbenv/shims```

To solve the problem I added to ~/.config/fish/config.fish : 
```
set PATH $HOME/.rbenv/shims $PATH
```
Which seems to solve problems

Do you need any other details ?
If you need, I can try on a mac os X 10.10 (not the recent one)

Thank you

**Comment by mislav** [comment]
Sorry you're having problems. Can you try with the most recent version of rbenv from the master branch? E.g. if you've installed rbenv as git clone to `~/.rbenv` you can just go there and do a `git pull` to update to latest master.

**Comment by Hettomei** [comment]
Hi,
 
I was currently on 
OS X 10.9.5 
  (not ubuntu), 
installed via homebrew 
  (wich download the tagged 0.4 version)
with fish 2.2.0

The bug was here (and the solution worked).

Now I completely removed rbenv from homebrew and do a git clone https....rbenv in .rbenv : The bug is still here and I have to do add ```set PATH $HOME/.rbenv/shims $PATH``` to make it works.

My full fish.config : 

```fish
set PATH $HOME/.rbenv/bin $PATH
set PATH $HOME/.rbenv/shims $PATH
. (rbenv init -)
```

**Comment by mislav** [comment]
If you type just `rbenv init -` in your fish shell, what is the output? This should be the first line of it:

```fish
setenv PATH '/opt/boxen/rbenv/shims' $PATH
```

It's really bizarre that you're forced to provide that line manually. It shouldn't be needed.

**Comment by Hettomei** [comment]
Here is the full output

```bash
> echo $PATH
/Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
> ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
> rbenv global
2.2.2
> rbenv init -
setenv PATH '/Users/tim/.rbenv/shims' $PATH
setenv RBENV_SHELL fish
. '/Users/tim/.rbenv/libexec/../completions/rbenv.fish'
rbenv rehash 2>/dev/null
function rbenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    eval (rbenv "sh-$command" $argv)
  case '*'
    command rbenv "$command" $argv
  end
end
> ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
> rbenv global
2.2.2
> echo $PATH
/Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
```

Put If I write "by hand" $PATH is changed : 

```bash
> ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
> echo $PATH
/Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
> setenv PATH '/Users/tim/.rbenv/shims' $PATH
> echo $PATH
/Users/tim/.rbenv/shims /Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
> ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
```

**Comment by mislav** [comment]
Just calling `rbenv init -` in your shell will not actually change the PATH. The output of the script needs to be eval'd, and that's what the `. (rbenv init -)` syntax is for.

What if your fish.config looks like this:

```fish
set PATH $HOME/.rbenv/bin $PATH
. (rbenv init -)
```

and you start a new shell and check PATH?

**Comment by Hettomei** [comment]
I found a new way to make it works without updating $PATH : 

in config.fish
```fish
rbenv init - | source -
```
```fish
> echo $RBENV_SHELL 
fish
> echo $PATH
/Users/tim/.rbenv/shims /Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
```

So there is a difference between ". (rbenv init -)" and "rbenv init - | source -"

Should I make a PR to add this command to readme.md ?

**Comment by Hettomei** [comment]
To answer to your

> What if your fish.config looks like this:
>
> set PATH $HOME/.rbenv/bin $PATH
> . (rbenv init -)

That was my basic configuration. And this didn't worked and my $PATH was : 
```bash
> echo $PATH
/Users/tim/.rbenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
```

**Comment by mislav** [comment]
> So there is a difference between `. (rbenv init -)` and `rbenv init - | source -`

Oh, interesting. I never knew. The original syntax seemed to work for other fish users. We still don't understand why it didn't work for you. Might we know more about your fish version, how you installed it, and configuration?

I'll have to first look into whether `rbenv init - | source -` is a perfect equivalent and covers all the bases for all the fish users before I OK the change. But you're welcome to start on a PR.

**Comment by Hettomei** [comment]
As said before, my fish version is "fish 2.2.0"

I try to be more precise : 

+ I ran in the exactly same issue on Ubuntu 14.04 and OS X 10.9
+ on mac, I installed fish with ```brew install fish```
+ on ubuntu, I installed fish with ```sudo apt-add-repository ppa:fish-shell/release-2 && sudo apt-get install fish```
+ Both ran ```rbenv``` from master
+ Both failed with ```. (rbenv init -)``` and both works with ```rbenv init - | source -``` (that mean, $PATH and $RBENV_SHELL are well updated)

**Comment by mislav** [comment]
@Hettomei I just checked what our actual fish instructions were 31fab8cdaebf4bb47d078a92154a09d0e0deccf4 and it seems we missed a key element:

```fish
status --is-interactive; and . (rbenv init -|psub)
```

I think the `psub` part is needed.

**Comment by Hettomei** [comment]
Hi,

I confirm that ```. (rbenv init -|psub)``` in config.fish works well. Sorry for the inconvenience.

I didn't see this command in readme nor in wiki, did I miss something ?

**Comment by mislav** [comment]
Where did you get the initial command that you pasted in your fish config? Let's find where it comes from and fix it.

**Comment by lowski** [comment]
I also have a problem with fish and rbenv. When I add `. (rbenv init -|psub)` to `config.fish` I get:

```shell
fish: Unknown command 'getopt -T'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish (line 7): 	if getopt -T >/dev/null
                                                                      	   ^
in function 'psub'
	called on line 1 of file ~/.config/fish/config.fish

in command substitution
	called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

env: bash: No such file or directory
fish: Unknown command 'getopt -n psub -Q -o hf -l help,file --'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish (line 11): 	if not getopt -n psub -Q $shortopt $longopt -- $argv >/dev/null
                                                                       	       ^
in function 'psub'
	called on line 1 of file ~/.config/fish/config.fish

in command substitution
	called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command 'getopt -o hf -l help,file --'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish (line 1): getopt $shortopt $longopt -- $argv
                                                                      ^
in command substitution
	called on line 3 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish

in function 'psub'
	called on line 1 of file ~/.config/fish/config.fish

in command substitution
	called on line -1 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command 'mktemp /var/folders/__/m6wpbv_j5ylbv1gtyq4wsz180000gn/T//.psub.XXXXXXXXXX'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish (line 1): mktemp "$TMPDIR[1]"/.psub.XXXXXXXXXX
                                                                      ^
in command substitution
	called on line 3 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish

in function 'psub'
	called on line 1 of file ~/.config/fish/config.fish

in command substitution
	called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command 'cat'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/psub.fish (line 59): 		cat >$filename
                                                                       		^
in function 'psub'
	called on line 1 of file ~/.config/fish/config.fish

in command substitution
	called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command 'rm'
~/.config/fish/config.fish (line 1): command rm $filename

in function '__fish_psub_16776'
	called on line 1 of file ~/.config/fish/config.fish
	with parameter list 'JOB_EXIT 2 0'

in event handler: exit handler for job 2, 'and . (rbenv init -|psub)'

```

**Comment by krzkrzkrz** [comment]
Had the same issue. I can confirm `status --is-interactive; and . (rbenv init -|psub)` works.

I installed rbenv via homebrew. i.e. `brew install rbenv --HEAD`

Maybe we should update the README to avoid confusion

**Comment by mislav** [comment]
The instructions for fish are already correct:

```
$ rbenv init fish
# Load rbenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and . (rbenv init -|psub)
```
