### ISSUE TITLE
Installed rbenv > ruby 2.2.0 > Gem issue

### ISSUE THREAD

**Issue by mramitpatel** [sstephenson/rbenv#761]
This might be a gulp, gem or overall rbenv issue...
Rbenv is running and I'm able to switch versions, which is great. When I run 'gulp' on my build, I get a bunch of errors like this:

```
/Users/amit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sass-3.4.16/lib/sass/script/tree/variable.rb:49:in ``_perform'

/Users/amit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sass-3.4.16/lib/sass/script/tree/node.rb:50:in ``perform'
```

What am i doing wrong?

**Comment by mislav** [comment]
Hi @mramitpatel,

I can't tell what's wrong with your environment, but this is most likely due to your gulp/RubyGems setup and not with rbenv. rbenv only switches Ruby versions and it's very unlikely that it's responsible for runtime errors inside Ruby programs.
