### ISSUE TITLE
rbenv install fails

### ISSUE THREAD

**Issue by razagill** [sstephenson/rbenv#766]
Hi,
I'm trying to install ruby 2.2.2 on OSX like so:
```
rbenv install 2.2.2
```
However, I'm getting this error:
```
Downloading ruby-2.2.2.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
Installing ruby-2.2.2...
mkdir: /opt/local/lib: Permission denied

BUILD FAILED (OS X 10.10.4 using ruby-build 20150803)

Inspect or clean up the working tree at /var/folders/ch/1dh6ks8d6_59nxs7tlddvy8m0000gn/T/ruby-build.20150808082103.12885
Results logged to /var/folders/ch/1dh6ks8d6_59nxs7tlddvy8m0000gn/T/ruby-build.20150808082103.12885.log

Last 10 log lines:
Last-Modified: Mon, 13 Apr 2015 20:10:53 GMT
ETag: "326e99ddc75381c7b50c85f7089f3260"
Accept-Ranges: bytes
Server: AmazonS3
Age: 46823
X-Cache: Hit from cloudfront
Via: 1.1 f4879b16ae11c9a08a3038de5ea0df75.cloudfront.net (CloudFront)
X-Amz-Cf-Id: n3_3wrZQpWBHIo0F2prTE-DunSYld-DE_vEQ_Svtw8DrGfGeqvglNg==

/var/folders/ch/1dh6ks8d6_59nxs7tlddvy8m0000gn/T/ruby-build.20150808082103.12885/ruby-2.2.2 /var/folders/ch/1dh6ks8d6_59nxs7tlddvy8m0000gn/T/ruby-build.20150808082103.12885 ~
```
I haven't tried it with `sudo` although the error is about denial of permission in `/opt/local/lib`. I'm not sure should I do that or is there another right way of getting it installed?

**Comment by mislav** [comment]
Can you check if you have something like `-L/opt/local/lib` in your LDFLAGS environment variable and remove it prior to `rbenv install` please? Maybe simply use this:

```sh
LDFLAGS= rbenv install 2.2.2
```

**Comment by mislav** [comment]
If you still have problems, please search existing issues at https://github.com/sstephenson/ruby-build/issues or open a new ticket. Thanks!

**Comment by Osram-Lux** [comment]
Hi Mislav,

     LDFLAGS= rbenv install 2.3.3

solved exactly this problem for me.

**Comment by alexandru** [comment]
👋

This issue happens to me too, and I have the following in my `.zshrc`:
```bash
export LDFLAGS="-L/usr/local/opt/mysql-client/lib"
```

In my opinion, `rbenv` shouldn't try to install stuff in `/usr/local/opt` due to the settings of another completely unrelated program.

BTW, thanks for all your hard work ❤️

Cheers,
