### ISSUE TITLE
rbenv is not caching downloaded version of Ruby

### ISSUE THREAD

**Issue by annetsi** [sstephenson/rbenv#772]
I had issues installing Ruby, so I had to rerun the process for several times. Why is it not caching the downloaded file? The `curl` process was running for several minutes each time.

**Comment by mislav** [comment]
I'm sorry about the slowness. Caching isn't on by default, but if you create a `cache` directory within rbenv, caching downloads will be on by default. Simply do:

```
$ mkdir `rbenv root`/cache
```
