### ISSUE TITLE
eval $(rbenv init -) requires superuser 

### ISSUE THREAD

**Issue by shreyharia** [sstephenson/rbenv#774]
When I open my shell it gives me an error saying 'init'  requires superuser privilege. Well I don't have it that on my machine. How do I go about it?

**Comment by mislav** [comment]
Normally, `rbenv init` shouldn't require superuser privileges. Maybe somebody who installed rbenv on this machine gave execution bits for `rbenv-init` command to just superusers?

Can you paste your exact rbenv configuration from your shell rc file? Thanks

**Comment by shreyharia** [comment]
I am sorry! this was happening because my machine wasn't configured to use bash. It doesn't require superuser permission. Thanks.
