### ISSUE TITLE
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"

### ISSUE THREAD

**Issue by dcalixto** [sstephenson/rbenv#775]
Installing eventmachine 1.0.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

/Users/danielcalixto/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150902-42332-1kloes5.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
CFLAGS= -O3 -Wno-error=shorten-64-to-32 -pipe -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
CPPFLAGS=-I/Users/danielcalixto/.rbenv/versions/2.2.2/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
cc1plus: error: unrecognized command line option "-Wno-ignored-qualifiers"
cc1plus: error: unrecognized command line option "-Wno-unused-result"
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/danielcalixto/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8 for inspection.
Results logged to /Users/danielcalixto/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-11/2.2.0-static/eventmachine-1.0.8/gem_make.out
An error occurred while installing eventmachine (1.0.8), and Bundler cannot continue.
Make sure that gem install eventmachine -v '1.0.8' succeeds before bundling.

**Comment by dcalixto** [comment]
this is a eventmachine or rbenv problem?

**Comment by XtianB** [comment]
That last line may actually serve as a clue...was this done all in one build including your installation of Ruby, rbenv? Maybe something was installed out of order. Initially thought of something else. . . :-\

**Comment by XtianB** [comment]
Problem is eventmachine install from what I can make of it

**Comment by hsbt** [comment]
It's your development environment or eventmachine configuration problem.  Please submit issue  eventmachine repository.

**Comment by dcalixto** [comment]
is not my environment because the eventmachine 1.0.7 install without problem. is the eventmachine 1.0.8 or the rbenv.

**Comment by hsbt** [comment]
see https://github.com/eventmachine/eventmachine/compare/v1.0.7...v1.0.8#diff-b3c266c0a40fd6ea5ce51093b147dbe6R183

eventmachine 1.0.8 changed compile option. you need to choice following solutions:

 * upgrade your compiler on your development environment
 * submit patch to eventmachine
 * use eventmachine-1.0.7

**Comment by dcalixto** [comment]
@hsbt i open a issue already on eventmachine to aware the guys about this.
i gonna update my compiler to check it out.

**Comment by mislav** [comment]
@dcalixto Sorry you're having problems. If the problem proves to be with EM, please close this ticket. Thanks!

**Comment by dcalixto** [comment]
yes the problem is with EM
