### ISSUE TITLE
Ruby version bundler sees is not the version rvm and Gemfile recognizes so bundle install fails

### ISSUE THREAD

**Issue by kristina-apl** [sstephenson/rbenv#777]
What is happening when I run bundle install:  Error Message when trying to run bundle install under the application user account:

```
     Your Ruby version is 1.9.3, but your Gemfile specified 2.1.3
```

What I expect: Bundler will recognize that my version number that was set by RVM is 2.1.3 and continue installing my gems.

I do not have version 1.9.3 installed on my system.  When I run $ruby -v it does show 2.1.3p242.  Also when I run $rvm info it shows that only 2.1.3 is the only version installed.  In trying to track this down I found an issue with versioning of bundler first.  On my admin account where I did my first installed bundler it downloaded and recognizes that I have version 1.10.6.  However when I type $bundler -v on my user account it shows that an old version (1.7.3) is there (wondering if it was installed at the same time the OS was, which is Ubuntu 14.04 server).  I ran gem install bundler under the application user account it successfully installed version 1.10.6 again.  However it still only recognizes 1.7.3 when I type bundler -v again.  I tried to uninstall the 1.7.3 version but I am getting the message that it is not installed.

Here is my Gemfile content:

```rb
source 'http://rubygems.org'
ruby '2.1.3'

#ruby-gemset=pfinder

gem 'rails', '4.2.0.beta2'
gem 'arel', '6.0.0.beta2'
gem 'sass-rails', '5.0.0.beta1'
gem 'bootstrap-sass', '3.2.0.0'
gem 'sprockets', '2.12.2'
gem 'bcrypt', '3.1.7'
gem 'faker', '1.4.2'
gem 'will_paginate', '3.0.7'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'mini_portile', '0.6.0'
gem 'uglifier', '2.5.3'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.2'
gem 'turbolinks', '2.3.0'
gem 'jbuilder', '2.1.3'
gem 'rails-html-sanitizer', '1.0.1'
gem 'sdoc', '0.4.0', group: :doc
gem 'yaml_db'
gem 'json'
gem 'elasticsearch-model', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
gem 'elasticsearch-rails', git: 'git://github.com/elasticsearch/elasticsearch-rails.git'
gem 'mysql2', '0.3.18'
gem 'passenger', '5.0.16'

group :development do
        gem 'mysql2', '0.3.18'
        gem 'byebug', '3.4.0'
        gem 'web-console', '2.0.0.beta3'
        gem 'spring', '1.1.3'
end

group :test do
        gem 'minitest-reporters', '1.0.5'
        gem 'mini_backtrace', '0.1.3'
        gem 'guard-minitest', '2.3.1'
end
```

Thanks,
Kris

**Comment by mislav** [comment]
Hi, sorry for the late reply. You seem to have issues with RVM, which is a Ruby version manager completely separate from "rbenv". It would seem that you've opened the issue in the wrong project.

With rbenv, you would have to ensure that your project is configured locally to use a Ruby version that matches the one specified in your Gemfile. To do that, you would use:

```
$ rbenv local 2.1.3
```

That writes out a `.ruby-version` file in your project that configures the version manager to always use Ruby 2.1.3 for your project.
