### ISSUE TITLE
gcc-4.9: error: unrecognized command line option '-V' on rbenv install 1.8.7-p374

### ISSUE THREAD

**Issue by Nakilon** [sstephenson/rbenv#778]
I want to install Ruby of an old version the same as at Travis CI available:

~~~
$ rbenv install 1.8.7-p374
Downloading ruby-1.8.7-p374.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/876eeeaaeeab10cbf4767833547d66d86d6717ef48fd3d89e27db8926a65276c
Installing ruby-1.8.7-p374...

BUILD FAILED (OS X 10.9.4 using ruby-build 20150818)
...
configure: error: C compiler cannot create executables
See `config.log' for more details
...
~~~

Here is `config.log`:
~~~
...
Thread model: posix
gcc version 4.9.2 (Homebrew gcc 4.9.2_1) 
configure:3191: $? = 0
configure:3180: /usr/local/bin/gcc-4.9 -V >&5
gcc-4.9: error: unrecognized command line option '-V'
gcc-4.9: fatal error: no input files
compilation terminated.
...
~~~

**Comment by Nakilon** [comment]
The same with ruby-1.9.2-p330

**Comment by Nakilon** [comment]
Fixed by sudo removing from `/usr/local/bin/ruby-build` those lines https://github.com/gnprice/ruby-build/commit/9c3e1644e9b668dcf39755c9317c0b0a1e6ff5aa that add clang flags to `/usr/local/bin/gcc-4.9` that is used when I do `rbenv install`.

**Comment by mislav** [comment]
Glad you solved it. Since this is a ruby-build issue, please post future updates in existing https://github.com/sstephenson/ruby-build/issues tickets or open a new one.
