### ISSUE TITLE
OS X Homebrew: `open-uri` fails with 

### ISSUE THREAD

**Issue by acjay** [sstephenson/rbenv#779]
I ran into a situation where using `open-uri` to pull data from HTTPS was failing with the error

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

, even when browsers would open the same URI without issue. Running `openssl s_client -host <host> -port <port>` was succeeding, but running ``` `brew --prefix openssl`/bin/openssl ...``` was failing to verify the host. It seems this is because the browser uses the OS's certificates which aren't stored in the typical OpenSSL manner, but Ruby is linked with Homebrew's OpenSSL, which has certificates that can be out of sync with the rest of the system. I tried reinstalling `openssl` via Homebrew to try to resync the certificates with my OS X certificates and reinstalling Ruby 2.2.3 via `rbenv`, but to no avail.

Eventually, I succeeded by reinstalling following the instructions in the to post https://github.com/rubinius/rubinius/issues/3478, with my preferred version of Ruby.

I'm not sure this is a `rbenv` issue or a https://github.com/sstephenson/ruby-build issue, but thought I would mention here for people who run into the same thing.

**Comment by DomT4** [comment]
> I tried reinstalling openssl via Homebrew to try to resync the certificates with my OS X certificates

Just FYI, you can `brew postinstall openssl` rather than reinstalling the whole thing. Cert regeneration is done locally after installation.

**Comment by mislav** [comment]
@DomT4: that's a good tip. Unfortunately, that's the best solution we have right now. Ruby on OS X will usually link against Homebrew openssl which writes out certificates at a set point in time. After a few years, these certificates are bound to get out of date. We don't have any better solution for this right now. Apple's system openssl is patched to pull certificates from Keychain dynamically, but sadly that openssl version doesn't work with newer Rubies.
