### ISSUE TITLE
Bundler can't install gems

### ISSUE THREAD

**Issue by zedalaye** [sstephenson/rbenv#784]
This is what I get during ```$ cap production deploy ```

```
INFO [ccc718b1] Running ~/.rbenv/bin/rbenv exec bundle install --path /usr/local/webapps/appname/shared/bundle --without development test --deployment --quiet as deploy@server
DEBUG [ccc718b1] Command: cd /usr/local/webapps/appname/releases/20150918220859 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.7 ~/.rbenv/bin/rbenv exec bundle install --path /usr/local/webapps/appname/shared/bundle --without development test --deployment --quiet )
DEBUG [ccc718b1] 	An error occurred while installing RedCloth (4.2.9), and Bundler cannot
DEBUG [ccc718b1] 	continue.
DEBUG [ccc718b1] 	Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@server: bundle exit status: 5
bundle stdout: An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
bundle stderr: Nothing written

SSHKit::Command::Failed: bundle exit status: 5
bundle stdout: An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
bundle stderr: Nothing written

Tasks: TOP => deploy:updated => bundler:install
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@server: bundle exit status: 5
bundle stdout: An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
bundle stderr: Nothing written
```

The gem can be installed without problem when I run ```gem install RedCloth```

When I run the bundler command by hand while logged on the server I get the exact same error :

```
deploy@server:/usr/local/webapps/appname/releases/20150918220859$ RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.7 ~/.rbenv/bin/rbenv exec bundle install --path /usr/local/webapps/appname/shared/bundle --without development test --deployment --quiet

An error occurred while installing RedCloth (4.2.9), and Bundler cannot continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.```

**Comment by zachbc** [comment]
See if this helps (same exit status and also uses "cap production deploy":

http://stackoverflow.com/questions/26477139/bundler-fails-with-cap-production-deploy

**Comment by mislav** [comment]
Sorry, we can't help you with gem installation on your servers. The problem is most likely in missing libraries on your system or in this gem's build system itself. The only responsibility of rbenv is to switch between Ruby versions.

BTW, if you added `~/.rbenv/bin` and `~/.rbenv/shims` to your PATH and ran `rbenv rehash`, you would be able to run `bundle install` directly without the need for `~/.rbenv/bin/rbenv exec`. Please see our installation and usage instructions in the README.

**Comment by zedalaye** [comment]
I got it : bundle had to install gems in a specific path (bundle install --path...) and that path was mounted from an NFS share with the option "noexec".
When bundle compiles gem extensions, it generates small executables to check compiler features and run these executables to make sure they work as expected. When these executables are created on a "noexec" NFS share, nothing works.

**Comment by mislav** [comment]
Thanks for the update! Glad you sorted it out.
