### ISSUE TITLE
Can't install Ruby version in Fish shell

### ISSUE THREAD

**Issue by krzkrzkrz** [sstephenson/rbenv#785]
Using the Fish shell. I also installed rbenv HEAD. via: `brew install rbenv --HEAD`

I have `. (rbenv init -|psub)` in `~/.config/fish/config.fish`.

I do `echo $PATH`, I see:

```
/Users/chris/.nvm/versions/node/v0.12.2/bin /Users/chris/.rbenv/shims /Users/chris/.rbenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

You notice that:
1) `/Users/chris/.rbenv/shims` is in the `$PATH` twice. Is that normal?
2) `.rbenv/bin` is missing

When I do `rbenv install 2.1.6`, `rben global 2.1.6` and then `rbenv versions`, it shows:

```
* 2.1.6 (set by /Users/chris/.rbenv/versions/.ruby-version)
```

`ruby -v` also confirms `2.1.6`.

But when I open a new Fish shell. `ruby -v` outputs the old Ruby version and 

```
rbenv versions`
* system (set by /Users/chris/.rbenv/version)
```

What is going on? Did I miss something?

**Comment by krzkrzkrz** [comment]
Ok seems to work now. I restarted and `rbenv versions` is now selecting 2.1.6 on new shells. I also had to do `rbenv init fish`, which gave me instructions to add `status --is-interactive; and . (rbenv init -|psub)` to `~/.config/fish/config.fish`. Perhaps we should include this in the README

Also `echo $PATH` outputs `/Users/chris/.rbenv/shims` but not `/Users/chris/.rbenv/bin`. Since everything seems to work now, I am assuming thats fine.

Closing for now.

**Comment by mislav** [comment]
Thanks for updating!

**Comment by sunapi386** [comment]
I use fish shell. Somehow in the `~/.rbenv` folder, it was empty. 

So for me `rm -r ~/.rbenv` and redoing `rbenv install 2.4.1` and `rbenv global 2.4.1` did it. 

Make sure to have `status --is-interactive; and source (rbenv init -|psub)` in your `config.fish` because otherwise `which ruby` shows `/Users/<user>/.rbenv/shims//ruby` (notice the `//`).
