### ISSUE TITLE
Global or local

### ISSUE THREAD

**Issue by krzkrzkrz** [sstephenson/rbenv#786]
Just checking in.

If I want to have a specific Ruby version in all my shells. Do I use global or local? I am assuming the former.

In RVM, I was used to `rvm use 2.1.6 --default`. Is `rbenv global 2.1.6` the equivalent command?

**Comment by mislav** [comment]
Yes `rbenv global` is what you want. The other option is per-project `rbenv local` setting which writes out a `.ruby-version` file which selects the version for the current directory and all its subdirectories.

**Comment by krzkrzkrz** [comment]
Thanks for clearing that up
