### ISSUE TITLE
Deprecated warning - Mime::JSON

### ISSUE THREAD

**Issue by frgooall** [sstephenson/rbenv#789]
Dev Env - **Rails 5 & Ruby 2.2.3**
Not sure if this is being addressed, but I am using Rails 5 and starting the server produce the following;

`DEPRECATION WARNING: Accessing mime types via constants is deprecated.  Please change: 
  Mime::JSON to: Mime::Type[:JSON]
. (called from <class:JbuilderHandler> at /Users/fritz_laptop/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jbuilder-2.3.1/lib/jbuilder/jbuilder_template.rb:173)`

The warning goes away when I edited the file per warning message.

**Comment by thomasjo** [comment]
This is a problem with a gem (looks like jbuilder), not rbenv. Please close this issue, and open a new issue at https://github.com/rails/jbuilder. As you can see there, someone has tried to submit a PR to resolve the problem https://github.com/rails/jbuilder/pull/293.

**Comment by mislav** [comment]
Thanks @thomasjo!

**Comment by frgooall** [comment]
Okay, thanks! Will do.

**Comment by anji7686** [comment]
Deprecated accessing mime types via constants (eg. Mime::HTML). Use the subscript operator with a symbol instead (eg. Mime[:html])

[](https://github.com/rails/rails/pull/21869)
