### ISSUE TITLE
rbenv on El Capitan does not honor .ruby-version

### ISSUE THREAD

**Issue by groue** [sstephenson/rbenv#791]
Hello,

This script `testRubyVersion` has a weird behavior on El Capitan:

```ruby
#!/usr/bin/env ruby
puts RUBY_VERSION
```

Assuming the following rbenv setup:

    ~/.ruby-version : system
    ~/Documents/Project/.ruby-version: 2.1.1

On OSX 10.10 Yosemite:

```sh
yosemite:~$ ./testRubyVersion # Expect the system version
2.0.0
yosemite:~/Documents/Project/$ ../../testRubyVersion # Expect 2.1.1
2.1.1
```

And this is good. On OSX 10.11 El Capitan, we get:

```sh
elcapitan:~$ ./testRubyVersion # Expect the system version
2.0.0
elcapitan:~/Documents/Project/$ ../../testRubyVersion # Expect 2.1.1
2.0.0
```

And this is not good. It has become impossible to write a script which starts with `#!/usr/bin/env ruby` and uses the local ruby version.

Is it a bug? It there an alternative way of acheiving the same result?

Thanks in advance

**Comment by mislav** [comment]
Is your login shell zsh? Can you confirm that rbenv `shims` is in PATH and has precedence over system paths such as `/usr/bin`? Thanks

**Comment by groue** [comment]
Hello,

My shell is bash, and my $PATH has ${HOME}/.rbenv/shims on its left part.

For more details:

```sh
$ rbenv --version
rbenv 0.4.0
$ env
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TERM_PROGRAM_VERSION=361
USER=XXX
PATH=/Users/XXX/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/XXX
SHLVL=1
LOGNAME=XXX
_=/usr/bin/env
```

**Comment by groue** [comment]
To be honest, I'd prefer the script to always pick the same ruby version, but I don't know how to do that. The .ruby-version helped, but it is kind of a hack: under yosemite, each directory where I wanted to run the script had to have its .ruby-version file so that the script would run in the correct ruby version. It's mistake-prone, plus it forces the ruby version of the directory just for the sake of being able to run a general-use script.

If I had to rewrite my question, it would be:

Can rbenv help writing a ruby script that requires a specific ruby version whatever the directory it is run in?

**Comment by mislav** [comment]
rbenv has a feature that it tries to execute a ruby script with whatever the local `.ruby-version` is specified in any of the parent directories of the script.

For example, if your `testRubyVersion` script was in path `/path/to/my/testRubyVersion`, and you executed `/path/to/my/testRubyVersion` script from any other directory, the version that would have precendence is `/path/to/my/.ruby-version` if it existed.

So the behavior you're seeing on El Capitan is actually correct. Maybe on Yosemite you still had an outdated version of rbenv? Please compare `rbenv --version`

**Comment by groue** [comment]
It was rbenv 0.4.0 in both case.

OK, if I sum up:

- The behavior of my former Yosemite was the incorrect one.
- The behavior or El Capitan is the correct one.
- If I want a script `/path/to/script` to always use a specific ruby version, all I need is to add a `.ruby-version` file in its directory, at `/path/to/.ruby-version`. Now if `/path/to/` is added to $PATH, the `script` command will always use that Ruby Version.

Actually @mislav you have answered both my questions. We still don't know why Yosemite had this strange behavior, but this question is a little out of topic actually. So many thanks to you!

**Comment by mislav** [comment]
Thanks for the update!
