### ISSUE TITLE
Support for multiple active Ruby versions.

### ISSUE THREAD

**Issue by sanscore** [sstephenson/rbenv#793]
There is a derivative project for Python that is called [pyenv](https://github.com/yyuu/pyenv) which has a very interesting feature. You can set multiple versions of python to be active when you set the version. For instance:

    $ pyenv global 2.7.10 2.6.9 3.5.0 3.4.3

Which will create several unique symlinks to the various versions of python. From the above example, the following commands will be available `python`, `python2`, `python2.6`, `python2.7`, `python3`, `python3.4`, and `python3.5`. Giving order precedence to the more generic names, so `python` points to 2.7.10, `python2` points to 2.7.10, and `python3` points to 3.5.0. (This also includes versioning various binaries like `pip` which follow the same name/numbering scheme.)

This feature comes in very handy when you want to test a project against multiple versions of python (usually with [tox](https://testrun.org/tox/latest/)). 

**I would like to be able to do the same with ruby.** (Emphasis because I've buried the lead a bit.) If we could have a similar feature, then working with multiple rubies would be easier (both through automation and manual testing).

I'll just acknowledge one issue that it could hinder implementing this feature, but I don't have a solution. That is, it may be necessary to modify the ruby build process. Sure, upstream changes could be made, but that would be limited to future versions of ruby.

I'll also acknowledge a previously closed issue which offers the sentiment, but without asking for a specific feature enhancement. [Issue #69: How should I use multiple rubies on a project with rbenv and bundler?](https://github.com/sstephenson/rbenv/issues/69)

**Comment by sanscore** [comment]
> I'll just acknowledge one issue that it could hinder implementing this feature, but I don't have a solution. That is, it may be necessary to modify the ruby build process. Sure, upstream changes could be made, but that would be limited to future versions of ruby.

I know that I am getting a head here, but I looked into this (non-)issue. Aside from running `./configure`, `make`, and `make install`, I don't have much experience with Make. Because of that lack of experience I wanted to look into finding a solution for my own edification. So, I went ahead and looked into building ruby with a custom name. `./configure`, as it turns out, has the `--program-suffix=` option, so it's fairly easy to get ruby1.9, ruby2.1, etc; `./configure [...] --program-suffix="${RUBY_VERSION}"`. I don't know if that's always baked into `configure` or if it's unique to building ruby. Anyway, if this information is at all helpful, it likely more pertinent to ruby-build than it is to rbenv.

**Comment by mislav** [comment]
@blueyed already suggested this feature for anyenv (an experimental Go replacement for rbenv) https://github.com/mislav/anyenv/issues/3

I left my comment there that I didn't understand why should different python versions be available simultaneously, when instead a program that wants to test against multiple versions can do a loop:

```sh
for ver in 2.1.6 2.2.0 rbx-2.5.8; do
  RBENV_VERSION=$ver bundle exec rake
done
```

This approach seems highly specific to Python culture and I'm reluctant to bake it in. However, is there something I could do to make this available through a plugin? For example, there is a proposal to add plugin hooks for version lookups https://github.com/sstephenson/rbenv/pull/739

**Comment by sanscore** [comment]
@mislav thanks for engaging me in this request. I've had some time to think about this request and would like to talk about the rationale behind `rbenv` and derivative tools. I'm glad you brought up `anyenv` as I didn't realize it existed, but a lot of my thoughts went directly to making `rbenv` and `pyenv` generic to any project. And, so, my thoughts became quite extensive and led me to think of `rbenv` in a new light.

The following discussion should maybe be moved over to anyenv, but I'll start by posting it here.

#### First a tangent on the state of python (and pyenv)
I've seen @blueyed on quite a few different python projects. While I've never interacted with him, based on his comments, he seems to be quite proficient and experienced python developer. More experienced than me anyway, so I'd defer python questions to him.

I think we can all agree that this feature makes sense for python. I would even say that it is necessary because Python has a tendency to breaking features between builds. The differences between say `python2` and `python3` are known by even the most novice Python developers and hoops have to be jumped through to support both. 

Differences between `python2.6` and `python2.7` are known by experienced developers, so they'll avoid features such as dict and set comprehensions. Differences between `python2.7.8` and `python2.7.9`, which updated the ssl module and negatively affected a lot of popular packages, are more annoying. Between different projects having limited python version support and writing your own projects the need to have multiple python available starts to make sense.

With Ruby, the community has been more cautious (or lucky). Changes between versions haven't broken compatibility, at least not in a big way. Old versions are not future-compatible, of course, so there is the need to test against multiple versions if you when you target support for those older versions. It's true that there's not a specific problem in the ruby community that one can point at and say, 'Hey, I **have** to have Ruby 2.2 and Ruby 1.9 available at all times', but if done well, I can't imagine an argument against having the ability to do so.

Furthermore, I don't think this need (or want) is limited to just python (and pyenv) nor do I think it is limited to programming languages. 

Hypothetically. Imagine that you have to maintain some ancient piece of software with an archaic, forgotten file format. Luckily you were able to find a Vim plugin that handles modifying the file nicely, but unfortunately, this plugin only works in Vim 6.3. Now, you don't want to use Vim 6.3 as your default editor, you'll want to have system/latest version for that. So, this would be a nice scenario for a project like {rb,py,any,*}env to come in manage multiple versions of vim.

#### Why we need {rb,py,any,*}env
Let's define `rbenv` (etc) in simple, certain terms. That is: `rbenv` is a tool dynamically correct a system's PATH.

But, why would we want to have a dynamic PATH variable? Let's define the problem we're trying to solve.

For scripting languages, specifically, this is almost becoming a necessity for everyone because the needs of operating system are more-often-than-not **do not** meet the needs of the developer. Which is especially true when the developer is trying to extend support for various versions. (For instance OSX Yosemite has `ruby 2.0.0p481` and `Python 2.7.6`.)

So, the problem is kind-of two fold. We don't want to use the system version of an application, but we also don't want to negatively affect the system by replacing that version. Of course, we could do this manually by downloading, building, and installing to our `$HOME` directory (or `/opt/` or `/usr/local/`), but it wouldn't it be nicer to have a tool do this for us; ruby-build. 

Then once we have more than one version of our application, now we need a tool to help us get the desired version on any given invocation; rbenv.

I think it's important at this time to answer, what kind of tool are we describing? The combination of rbenv and ruby-build (because why wouldn't you have `ruby-build`!?), I would consider to be an `application-specific package manager`.

(An aside: For the longest time I could not figure out why one would want rbenv without ruby-build, until it hit me, doing ruby-core development!? That is modifying, building, and testing changes to MRI.)

Without having experienced `anyenv`, I feel that a generic version rbenv would be a lot like `brew` for OS X. Adding support for an application is going to require knowing about dependencies, where to download the source code, how to configure and build, where to install, etc. which is a `Formula` in Homebrew parlance.

Okay. That was a long diatribe that didn't really answer anything about the requested feature.

#### Why allow multiple active application versions

The problem I'm having with answering 'Why?'  is that I don't see a good reason to not arrogantly respond 'Why not?'

'Why not?' actually seems like an easier question for me to answer and to rebut.

**Issue:** User, or an application, incorrectly invocating the wrong application version.

From the user perspective, this seems easily manageable by convention as is done by pyenv (and as I did my best to describe above). The user would have organized the application versions by preference and the tools already exist to discover which versions are active (`version`, `versions`, `prefix`, `which`, `whence`).

Applications, however, will try to invoke the bare command, so what's to stop them, when calling `python`, from getting `python3` instead of the wanted `python2`. When I invoke `ipython`, an enhanced REPL replacement for `python`, how does it get the right version when multiple are active?

Imagine with this feature request fulfilled and you're working with fairly common gem; `thor` for arguments sake. Let's say the `rbenv global` returns `2.2.3 2.1.7 1.9.3` and `rbenv whence thor` would return `2.1.7 1.9.3`. For the user to be able to execute `thor` on `1.9.3` there would have to be a way to differentiate between the two. Suffixing binaries would be an intuitive solution, so we have `thor` (hits 2.1.7 because of order precedence rules), `thor-2.1.7`, and `thor-1.9.3`, but how would we prevent from `thor` executing in `ruby` (which is `ruby-2.2.3`). To prevent that possibility (and variations on the theme), `$PATH` would have to be restricted to just the one active environment instead of all three. Thus executing `thor-1.9.3` would have to eliminate the `ruby-2.2.3` and `ruby-2.1.7` from the `$PATH` to prevent funny business. 

> However, is there something I could do to make this available through a plugin?

To finally answer this question, it wouldn't bother me if this feature was a plugin instead of being a standard feature. I would suspect that in plugin form, it would have to do some extensive overriding of the standard functionality. Which, I would expect, would make it fragile.

Ultimately, I find it odd to be resistant to the feature because it expands an existing functionality and does nothing to detract from it. If the ability to have multiple active versions was added, it wouldn't force users to change their setups. All existing setups would continue to work as expected. 

I do see the argument for not wanting to do it yourself for whatever reason. It doesn't interest you; Not a feature you would use; Not going to attract more users; etc, so why invest your time? 

But, if the feature request was to be resolved in a pull-request, then an up-or-down vote would be revealing. Code issues aside. Does the request seem niche? Philosophically abhorrent?


@mislav Sorry for dropping such a long response on you. Obviously, I thought about this a while and most of these thoughts are completely tangential to the feature request. I respect your work and your ability to contribute to several different projects. It seems like every time I discover some cool, new project, you've already had several contributions to it. Needless to say, I have a lot of respect for you and await your response.

Please, feel free to correct me where my interpretation is wrong or inconsistent.

**Comment by mislav** [comment]
You are preaching to the choir when you talk to me about the importance of switching between isolated versions of installed software :)

So I definitely see where you're coming from, but I'm still not convinced. It sounds like we're both on the same page philosophically, but we're really talking about just syntax when we talk about version suffixes. Because this

```
$ ruby1.8
$ ruby2
$ ruby2.1
```

can already be expressed in rbenv in a more verbose format:

```
$ RBENV_VERSION=1.8.7 ruby
$ RBENV_VERSION=2.0.0 ruby
$ RBENV_VERSION=2.1.0 ruby
```

So you're basically asking for shortcuts, right? What we're talking about here could be accomplished with a simple binstub placed somewhere in the PATH:

```sh
$ cat bin/ruby2.1
#/bin/bash
exec RBENV_VERSION=2.1.0 ruby "$@"
```

Such binstubs could be generated by a plugin. But here's why I'm reluctant of adopting this approach in rbenv core. The version suffix style (like `ruby18`, `ruby19`) is a popular approach in some linux distros to having multiple different versions of the interpreter installed. But, rbenv implements a whole other approach of version switching— shims in the PATH and dynamic resolution of the version at invocation time with respect to $RBENV_VERSION and `.ruby-version` local files.

It seems like trying to maintain both versioning styles at the sime time would lead to confusion in two fronts: confusion of users as to what style do they need to pick when calling the ruby executable, and confusion of maintainers about trying to debug people's reports that something isn't working. I already spend considerable amount of my time helping people debug their shells and their PATH order and I shudder to think of implementing more complex features of rbenv that would be nontrivial to code up, debug, and maintain in the long run.

**Comment by mislav** [comment]
Closing for reasons outlined in my above comment.
