### ISSUE TITLE
are you serious guys?

### ISSUE THREAD

**Issue by x8core** [sstephenson/rbenv#794]
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...
Installed ruby-2.2.3 to /home/storm/.rbenv/versions/2.2.3

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

ARE YOU SERIOUS GUYS? The installation of Ruby takes a 10 MINUTES.

Am i just install GTA5, or Windows 7 or Mac OS?

**Comment by mislav** [comment]
Hi, rbenv project isn't responsible for installing rubies. Instead, [ruby-build project](https://github.com/sstephenson/ruby-build/issues) does that. Please report slowness issues there, together with more information about your system, such as linux distro and number of CPU cores.

How long did the download take?

Please note that you can speed up installation by skipping RDoc generation:

```sh
RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install ...
```

**Comment by vemv** [comment]
@x8core it's you who wasn't 'serious' by presuming all problems are easy to solve, and that rbenv folks just like slowness or whatever.

See https://github.com/sstephenson/ruby-build/issues/42

**Comment by ascendantlogic** [comment]
It's downloading and compiling the language runtime and standard libraries. If you'd like to speed up compiling the entirety of the Ruby language maybe you should head over to the Ruby core team and talk with them.
