### ISSUE TITLE
PATH error, gem executables will not run.

### ISSUE THREAD

**Issue by thibmaek** [sstephenson/rbenv#795]
I just switched to using rbenv instead of OS X ruby and got everything set up right (I suppose).
Settings are: 
```bash
echo $GEMPATH #~/.rbenv/versions/2.2.2/bin
which ruby #~/.rbenv/shims/ruby
which gem #~/.rbenv/shims/gem
```

I tried reinstalling my gems now with rbenv but got the following:
```bash
gem install teamocil
WARNING:  You don't have /Users/thibaultmaekelbergh/.gem/ruby/2.2.0/bin in your PATH,
	  gem executables will not run.
Successfully installed teamocil-1.2
1 gem installed
```

The gem is listed in `gem list` and when run displays the following error:
```bash
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'teamocil' (>= 0) among 108 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/thibaultmaekelbergh/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:324:in `to_spec'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/thibaultmaekelbergh/.gem/ruby/2.0.0/bin/teamocil:22:in `<main>'
```

**Comment by mislav** [comment]
Could you check for presence of `--user-install` in `/etc/gemrc` or `~/.gemrc`?

rbenv is not yet compatible with that. Could you remove that option if you don't absolutely need it?

**Comment by thibmaek** [comment]
Good to know! --user install was indeed in my .gemrc.
I removed the flag from it and now it works installing gems this way.

This means I still have to install it with sudo right?

**Comment by mislav** [comment]
No please don't install gems with sudo.

Rbenv works like this: you install (or symlink) Ruby versions into `` `rbenv root`/versions/ `` (typically `~/.rbenv/versions/`). These Ruby versions are owned by your user and don't require special permissions to install gems in. Then you just switch to the version that you want (`rbenv global 2.2.2`) and `gem install bundler` or whatever. If you already installed gems with sudo, please undo root-owned files with

```
sudo chown -R "${USER}:staff" `rbenv root`/versions
```

**Comment by lucy-itjob** [comment]
I have similar error, please help

+++++++
contegixs-MacBook-Pro:~ lucy$ which ruby
/Users/lucy/.rvm/rubies/ruby-2.4.0/bin/ruby
contegixs-MacBook-Pro:~ lucy$ which gem
/Users/lucy/.rvm/rubies/ruby-2.4.0/bin/gem

contegixs-MacBook-Pro:~ lucy$ gem install curb daemons ruby-termios net-ssh net-ssh-gateway gserver dnsruby --user-install
WARNING:  ****You** don't have /Users/lucy/.gem/ruby/2.4.0/bin in your PATH,**
	  gem executables will not run.
Building native extensions.  This could take a while...

In fact , I have did  set  ruby 2.4.0 path on .bashrc file and relogin to have the changes on the .bashrc file take effect, showing below
 
###############
echo 'export PATH=$PATH:~/.gem/ruby/2.4.0/bin' >> ~/.bashrc

contegixs-MacBook-Pro:~ lucy$ more ~/.bashrc
export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
#export PATH=$PATH:~/.gem/ruby/2.0.0/bin
source ~/.rvm/scripts/rvm
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH=$PATH:~/.gem/ruby/2.4.0/bin
#############

I also notice that there are no bin directory under /Users/lucy/.gem/ruby/2.4.0 directory

contegixs-MacBook-Pro:2.4.0 lucy$ ls -ltra ~/.gem/ruby/2.4.0/bin
ls: /Users/lucy/.gem/ruby/2.4.0/bin: No such file or directory

contegixs-MacBook-Pro:2.4.0 lucy$ pwd
/Users/lucy/.gem/ruby/2.4.0
contegixs-MacBook-Pro:2.4.0 lucy$ ls
build_info	doc		gems
cache		extensions	specifications
###########
How to resolve this warning below, please advise, thank you for the help in advance

WARNING:  ****You** don't have /Users/lucy/.gem/ruby/2.4.0/bin in your PATH,**
	  gem executables will not run.

**Comment by lucy-itjob** [comment]
also 
I try to restall ruby-2.4.0 on my Mac,

++++++
contegixs-MacBook-Pro:~ lucy$ rvm reinstall ruby-2.4.0
ruby-2.4.0 - #removing src/ruby-2.4.0..
ruby-2.4.0 - #removing rubies/ruby-2.4.0..
Searching for binary rubies, this might take some time.
**No binary rubies available for: osx/10.11/x86_64/ruby-2.4.0.**
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
+++++++++
Is this possible why my Mac do not have /Users/lucy/.gem/ruby/2.4.0/bin since my  Mac os is EI Capitan version 10.11.6

contegixs-MacBook-Pro:2.0.0 lucy$ ls -ltra /Users/lucy/.gem/ruby/2.4.0/bin 
ls: /Users/lucy/.gem/ruby/2.4.0/bin: No such file or directory

+++++++++
contegixs-MacBook-Pro:2.0.0 lucy$

**Comment by lucy-itjob** [comment]
How to resolve this warning below,  Is there any ruby compile with Mac os is EI Capitan version 10.11.6?

please advise, thank you for the help in advance

WARNING: You don't have /Users/lucy/.gem/ruby/2.4.0/bin in your PATH,
gem executables will not run.

**Comment by snowman** [comment]
> Could you check for presence of `--user-install` in `/etc/gemrc` or `~/.gemrc`?
> 
> rbenv is not yet compatible with that. Could you remove that option if you don't absolutely need it?

and don't forget to check `$HOME/.config/gem/gemrc`

```sh
$ sudo updatedb --verbose
$  locate gemrc | xargs grep '\--user-install' --color=always
```
