### ISSUE TITLE
any way to uninstall ruby using rbenv

### ISSUE THREAD

**Issue by pulkitnandan** [sstephenson/rbenv#797]
Didn't find any way on readme to remove ruby installed with rbenv.

**Comment by mislav** [comment]
Sorry about that. To uninstall a version e.g. "1.2.3", simply use ``rm -rf `rbenv root`/versions/1.2.3``. I'll see if we can work this into the README somehow.

**Comment by pulkitnandan** [comment]
This doesn't works for me and I'm stuck at removing ruby installed with rbenv, need a different version but each time it latched on the latest version, so I was wondering let start from the start and bring my linux just as it was before installing rbenv but failing each time here's the log

pulkitnandan@ubuntu:~$ rm -rf `rbenv root`/versions/1.2.3^C
pulkitnandan@ubuntu:~$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
pulkitnandan@ubuntu:~$ rm -rf `rbenv root`/versions/2.1.2p95
pulkitnandan@ubuntu:~$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]


Does it mean it needs atleast on ruby installed.

**Comment by mislav** [comment]
If you type `rbenv version`, you will get the actual name of the Ruby install. In your case it's probably "2.1.2". So the command would be:

    rm -rf `rbenv root`/versions/2.1.2

But if you want to completely uninstall rbenv, all you have to do is remove entire rbenv root directory and remove references to rbenv from your shell initialization files.

I'm not really sure whether you're trying to use another version of Ruby or uninstall rbenv from your system, though. What is your primary goal you were trying to achieve? What's preventing you from doing it?

**Comment by mislav** [comment]
The documentation for removing individual Ruby versions from rbenv was added in #188.
