### ISSUE TITLE
ruby-2.2.2 is not installed error even though it is

### ISSUE THREAD

**Issue by dukebd711** [sstephenson/rbenv#798]
I'm using rbenv to manage my rubies. I have a project that uses 2.2.2 with a .ruby-version file specifying this version. 2.2.2 was installed via rbenv and can be seen as an available version. However, when I change to that directory I get an error saying 2.2.2 is not installed but the ruby version still changes to 2.2.2.

    [duke@vm1 ~]$ rbenv versions
    * system (set by /home/duke/.rbenv/version)
      2.2.2
    [duke@vm1 ~]$ ruby -v
    ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
    [duke@vm1 ~]$ cat ~/ruby_222/.ruby-version
    2.2.2
    [duke@vm1 ~]$ cd ~/ruby_222/
    ruby-2.2.2 is not installed.
    To install do: 'rvm install ruby-2.2.2'
    [duke@vm1 ruby_222]$ ruby -v
    ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
    [duke@vm1 ruby_222]$ rbenv which ruby
    /home/duke/.rbenv/versions/2.2.2/bin/ruby

**Comment by mislav** [comment]
When reading the message:

```
ruby-2.2.2 is not installed.
To install do: 'rvm install ruby-2.2.2'
```

it looks like you have RVM installed as well. RVM and rbenv are not compatible. It seems that you have set up rbenv correctly, but there is still something that RVM tries to manage, most likely in your shell initialization files such as `.bashrc`. Please completely uninstall RVM following their instructions and report back. Thanks!

**Comment by dukebd711** [comment]
(Face Palm) Sorry, next time I'll read the error more closely.

**Comment by mislav** [comment]
OK let's close this for now. Please reopen if you have new issues.
