### ISSUE TITLE
failed to download -  curl option ?

### ISSUE THREAD

**Issue by erwin16** [sstephenson/rbenv#799]
trying to install ruby 

yves@MacMini: ~ $ rbenv install 2.2.2    ( same with 2.2.3 )
Downloading ruby-2.2.2.tar.gz...
/usr/local/bin/ruby-build: line 288: 82656 Trace/BPT trap: 5       curl -qsILf ${options} "$1" 1>&4 2>&1
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz
error: failed to download ruby-2.2.2.tar.gz

BUILD FAILED (OS X 10.11 using ruby-build 20150928)

it seems that my curl doesn't accept these options .. -qsILf  ,  I had to install brew with the -k option

**Comment by mislav** [comment]
Dup of https://github.com/sstephenson/ruby-build/issues/812
