### ISSUE TITLE
gem command just freezing

### ISSUE THREAD

**Issue by pironim** [sstephenson/rbenv#801]
Trying to understand the problem and can't figure out how resolve this issue
  gem --version - just freezing

Here what I have
$ which gem
/home/vladimir/.rbenv/shims/gem

$ rbenv which gem
/home/vladimir/.rbenv/versions/jruby-1.7.16.1/bin/gem

this happen when I set  export RUBYGEMS_GEMDEPS="-" in my .bashrc
I make a call from project directory ~/code/proj1 and it has Gemfile Gemfile.lock
and previous directory also has different Gemfile and Gemfile.lock

Not sure I have a correct configuration but why gem command is affected that is the question

**Comment by mislav** [comment]
What is RUBYGEMS_GEMDEPS supposed to do normally?

**Comment by pironim** [comment]
@mislav As far as I know this force rubygems to travel up and find other Gemfiles 
Here is some explanation https://github.com/rubygems/rubygems/blob/c18805ca48f533fbde40025df41a8f817cd6ff48/lib/rubygems.rb#L1021

In fact I just experimenting and trying to setup guard on the top level for several project - with no luck

**Comment by mislav** [comment]
This sounds like maybe JRuby and RubyGems version that ships with it might not be compatible with your Gemfile. Have you tried `bundle exec ruby -e0` to see if that works? Instead of `RUBYGEMS_GEMDEPS`, you could be using `bundle exec` instead.

**Comment by mislav** [comment]
@pironim Do you still have a problem which you believe rbenv is responsible for?

**Comment by pironim** [comment]
@mislav No. I remove RUBYGEMS_GEMDEPS and Gemfile from projects directory - and problem disappear.

**Comment by mislav** [comment]
Thanks for the update. Yes, it definitely seems that JRuby has a problem with RUBYGEMS_GEMDEPS. Not an issue with rbenv, it seems.
