### ISSUE TITLE
Bump version number to reflect bugfixes

### ISSUE THREAD

**Issue by TheLonelyGhost** [sstephenson/rbenv#803]
I would do this in a PR, but it's not exactly an option with tagging.

Since I installed rbenv with homebrew, I'd like to have a copy of the project without some key bugs (e.g., #543) since it has been pretty well established as stable. The last tagged release was over 2 years ago and there has been a lot of development since then.

Any reason not to just arbitrarily tag the current HEAD as 0.4.1?

**Comment by mislav** [comment]
Sorry, I've been slacking at a release.

I can't tag current version as 0.4.1 since it's full of major changes. Instead, I'll bump the major revision. I have to finish up the installer script. Stay tuned.

Until then you can `brew upgrade rbenv --HEAD`

**Comment by TheLonelyGhost** [comment]
:+1: for major release. Wasn't aware of the `--HEAD` option of homebrew so thanks for that too.
