### ISSUE TITLE
rbenv init not working correctly on fish?

### ISSUE THREAD

**Issue by dideler** [sstephenson/rbenv#810]
I recently installed rbenv 0.4.0 (and ruby-build, rbenv-default-gems, rbenv-gem-rehash) via Homebrew on a new machine running El Capitan. I also installed fish via Homebrew.

When trying to source `(rbenv init -|psub)`, from the line in my `~/.config/fish/config.fish`
```
status --is-interactive; and source (rbenv init -|psub)
```
I get the following error

```
'case' builtin not inside of switch block
/var/folders/w3/zy8qr25x79b6nm6tbx54p4sdhgzs2z/T//.psub.7wtbxWqVCZ (line 10):   case "$command" in
                                                                                ^
from sourcing file /var/folders/w3/zy8qr25x79b6nm6tbx54p4sdhgzs2z/T//.psub.7wtbxWqVCZ
	called on line 20 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

It doesn't look like `rbenv init` is returning the correct results for fish:
```
↪ rbenv init - fish
export PATH="/Users/dideler/.rbenv/shims:${PATH}"
rbenv rehash 2>/dev/null
rbenv() {
  typeset command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval `rbenv "sh-$command" "$@"`;;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

**Comment by mislav** [comment]
Sorry, 0.4.0 is very old and didn't have fish support yet! It was added in #434. You should `brew upgrade rbenv --HEAD` to get the edge version from master.

**Comment by dideler** [comment]
Thanks @mislav, that fixed it :heart:

**Comment by anthonylebrun** [comment]
I think I'm probably missing something @mislav I have the latest version of brew and:
```
plebrun> brew upgrade rbenv --HEAD
Error: rbenv HEAD already installed

plebrun> brew list --versions rbenv
rbenv 0.4.0 HEAD
```

**Comment by mislav** [comment]
@anthonylebrun `brew uninstall rbenv; brew install rbenv`

**Comment by anthonylebrun** [comment]
@mislav That worked. I owe you one!
