### ISSUE TITLE
rbenv violates XDG basedir spec on linux

### ISSUE THREAD

**Issue by sandys** [sstephenson/rbenv#811]
according to http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

rbenv is one of the most popular tools on Linux - it would be awesome if you guys could comply with the spec.

**Comment by mislav** [comment]
How do you expect rbenv to comply with the XDG spec?

**Comment by jasonkarns** [comment]
@sandys rbenv can be installed anywhere. Simply export `RBENV_ROOT` accordingly.

Though, personally, I don't think rbenv belongs under XDG_CONFIG_HOME. rbenv is an app, not a configuration file. I set `RBENV_ROOT=/usr/local/var/rbenv`

**Comment by mislav** [comment]
Agreed. Since `~/.rbenv` folder is mostly not configuration files (with exception of `~/.rbenv/version` global version file), I would say this doesn't fall under what XDG_CONFIG_HOME is supposed to be used. Closing until someone can argue otherwise.

**Comment by lgarron** [comment]
> Since ~/.rbenv folder is mostly not configuration files (with exception of ~/.rbenv/version global version file), I would say this doesn't fall under what XDG_CONFIG_HOME is supposed to be used.

It seems like they're mostly data files? `$XDG_DATA_HOME` exists for that.

**Comment by lgarron** [comment]
It still greatly disappoints me that the folder is hardcoded to `~/.rbenv`. Most programs now respect the XDG convention (or allow an env var to override their own default), and `rbenv` is one of the few remaining exceptions.

My last comment still feels relevant — there *is* an XDG convention for where to store data files.

**Comment by jasonkarns** [comment]
As mentioned earlier in this thread, the installation path is not hard coded. You can install it anywhere you like and set RBENV_ROOT accordingly.

**Comment by lgarron** [comment]
> As mentioned earlier in this thread, the installation path is not hard coded. You can install it anywhere you like and set RBENV_ROOT accordingly.

Hmm, last time I tried this, it didn't do what it was supposed to. But I think this may have been due to interactions with projects I no longer have to run locally, so I'll give it another go. 🤞

**Comment by hsbt** [comment]
`RBENV_ROOT=$XDG_DATA_HOME/rbenv` is completely working on my environment.

**Comment by akiva** [comment]
I would vote to see these changes implemented. It is not as simple as `RBENV_ROOT=$XDG_DATA_HOME/rbenv` since, as @mislav mentioned, the directory is a mix of things.

**Comment by xeruf** [comment]
Using the new `XDG_STATE_HOME` in the meantime, but would also appreciate proper support.
